FROM node:22-bookworm-slim AS build
WORKDIR /app
ARG NEXT_PUBLIC_RELAY_API_URL
ENV NEXT_PUBLIC_RELAY_API_URL=$NEXT_PUBLIC_RELAY_API_URL
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm","run","start"]
