import assert from "node:assert/strict";
import { readFile, access } from "node:fs/promises";
import test from "node:test";

test("agent management routes and legacy demo cleanup are shipped", async () => {
  const server=await readFile(new URL("../src/server.ts",import.meta.url),"utf8");
  const hub=await readFile(new URL("../src/agent-hub.ts",import.meta.url),"utf8");
  const cleanup=await readFile(new URL("../../../infra/postgres/migrations/003_remove_legacy_demo.sql",import.meta.url),"utf8");
  assert.match(server,/app\.get\("\/api\/v1\/agents"/);
  assert.match(server,/app\.patch\("\/api\/v1\/agents\/:id"/);
  assert.match(server,/app\.delete\("\/api\/v1\/agents\/:id"/);
  assert.match(server,/app\.get\("\/api\/v1\/media"/);
  assert.match(server,/app\.delete\("\/api\/v1\/media\/:id"/);
  assert.match(server,/media_in_use/);
  assert.match(server,/account_id=\$2 OR account_id IS NULL/);
  assert.match(server,/removeLegacyDemoData/);
  assert.match(server,/markStaleAgentsOffline/);
  assert.match(hub,/HEARTBEAT_TIMEOUT_SECONDS = 45/);
  assert.match(hub,/agent_heartbeat_timeout/);
  assert.match(hub,/status IN \('offline','revoked'\)/);
  assert.match(hub,/liveAgents\.get\(agent\.id\) !== socket/);
  assert.match(hub,/wa\.status='online'/);
  assert.match(hub,/outcome==="deferred"/);
  assert.match(hub,/event\.cursor\?\?start\+index/);
  assert.match(hub,/failedCursor/);
  assert.match(hub,/unsupported_event_kind/);
  assert.match(hub,/event\.kind==="contact_identity"/);
  assert.match(hub,/mergeContactIdentity/);
  assert.match(hub,/UPDATE messages SET conversation_id=\$1 WHERE conversation_id=\$2/);
  assert.match(hub,/UPDATE messages SET sender_contact_id=\$1 WHERE sender_contact_id=\$2/);
  assert.match(hub,/status=\$2::wa_account_status/);
  assert.match(hub,/\$2::wa_account_status='online'::wa_account_status/);
  assert.match(hub,/status_reason=CASE WHEN \$2='online' THEN NULL/);
  assert.match(hub,/last_connected_at=CASE WHEN \$2='online' THEN now\(\)/);
  assert.match(cleanup,/10000000-0000-4000-8000-000000000001/);
  await assert.rejects(access(new URL("../../../infra/postgres/migrations/002_seed_demo.sql",import.meta.url)));
});
