"use client";

import { ArrowDown, ArrowUp, Check, GripVertical, Plus, RefreshCw, RotateCcw, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

export type TemplateFormat="text"|"image"|"pdf"|"sc"|"pi"|"ci";
type BlockType="orderHeader"|"itemList"|"feeList"|"total"|"paymentSummary"|"shippingAddress"|"contactInfo"|"notes"|"divider"|"customText";
type ContactInfoField="name"|"firstName"|"lastName"|"company"|"location"|"email"|"phone";
type OrderBusinessStatus="quotation"|"pending_confirmation"|"pending_payment"|"paid"|"processing"|"shipped"|"completed"|"cancelled";
type Block={id:string;type:BlockType;label?:string;text?:string;statusLabels?:Partial<Record<OrderBusinessStatus,string>>;bold?:boolean;italic?:boolean;strikethrough?:boolean;monospace?:boolean;blankAfter?:boolean;fontSize?:"small"|"medium"|"large";textColor?:string;backgroundColor?:string;align?:"left"|"center"|"right";itemTemplate?:string;showProductImages?:boolean;imageSize?:"small"|"medium"|"large";contactFields?:ContactInfoField[]};
export type OrderTemplate={version:1;blocks:Block[]};
type RequestResult={response:Response;token:string};

const META:Record<BlockType,{name:string;description:string;repeatable?:boolean;required?:boolean}>={
  orderHeader:{name:"订单标题 / 编号",description:"显示订单标题和订单号"},itemList:{name:"商品列表",description:"自动重复订单商品",required:true},feeList:{name:"附加费用",description:"没有费用时自动隐藏"},total:{name:"订单总计",description:"显示计算后的总金额",required:true},paymentSummary:{name:"付款方式摘要",description:"显示订单选择的付款方式与 Profile",required:true},shippingAddress:{name:"收货地址",description:"没有地址时自动隐藏"},contactInfo:{name:"联系人信息",description:"显示联系人资料中的已选字段"},notes:{name:"订单备注",description:"没有备注时自动隐藏"},divider:{name:"分隔线",description:"分隔相邻内容",repeatable:true},customText:{name:"自定义文本",description:"支持插入订单变量",repeatable:true},
};
const TYPES=Object.keys(META) as BlockType[];
const ORDER_STATUS_LABELS:Array<{value:OrderBusinessStatus;name:string;defaultLabel:string}>=[
  {value:"quotation",name:"报价",defaultLabel:"Quotation"},{value:"pending_confirmation",name:"待确认",defaultLabel:"Order"},
  {value:"pending_payment",name:"待付款",defaultLabel:"Payment Due"},{value:"paid",name:"已付款",defaultLabel:"Paid Order"},
  {value:"processing",name:"处理中",defaultLabel:"Order"},{value:"shipped",name:"已发货",defaultLabel:"Shipped Order"},
  {value:"completed",name:"已完成",defaultLabel:"Completed Order"},{value:"cancelled",name:"已取消",defaultLabel:"Cancelled Order"},
];
const DEFAULT_STATUS_LABELS=Object.fromEntries(ORDER_STATUS_LABELS.map(item=>[item.value,item.defaultLabel])) as Record<OrderBusinessStatus,string>;
const DEFAULT_ITEM_TEMPLATE="{{index}}. {{title}} x {{quantity}} - {{price}} each - {{subtotal}}";
const DEFAULT_TEXT:OrderTemplate={version:1,blocks:[{id:"order-header",type:"orderHeader",label:"Order",statusLabels:DEFAULT_STATUS_LABELS,bold:true,blankAfter:true},{id:"items",type:"itemList",label:"Items:",itemTemplate:DEFAULT_ITEM_TEMPLATE,blankAfter:true},{id:"fees",type:"feeList",label:"Additional fees:",blankAfter:true},{id:"total",type:"total",label:"Total:",bold:true},{id:"payment-summary",type:"paymentSummary",label:"Payment:",blankAfter:true},{id:"notes",type:"notes",label:"Notes:"}]};
const DEFAULT_IMAGE:OrderTemplate={version:1,blocks:[{id:"order-header",type:"orderHeader",label:"Order",statusLabels:DEFAULT_STATUS_LABELS,fontSize:"large",textColor:"#FFFFFF",backgroundColor:"#153F2F",align:"left"},{id:"items",type:"itemList",label:"Items:",itemTemplate:DEFAULT_ITEM_TEMPLATE,fontSize:"medium",textColor:"#20372D",backgroundColor:"#F6F9F7",align:"left",showProductImages:true,imageSize:"medium"},{id:"fees",type:"feeList",label:"Additional fees:",fontSize:"small",textColor:"#20372D",backgroundColor:"#FAFCFB",align:"left"},{id:"total",type:"total",label:"Total:",fontSize:"large",textColor:"#FFFFFF",backgroundColor:"#153F2F",align:"left"},{id:"payment-summary",type:"paymentSummary",label:"Payment:",fontSize:"medium",textColor:"#20372D",backgroundColor:"#EEF6F2",align:"left"},{id:"notes",type:"notes",label:"Notes:",fontSize:"small",textColor:"#20372D",backgroundColor:"#FFFAF0",align:"left"}]};
const CONTACT_FIELDS:Array<{value:ContactInfoField;name:string;sample:string}>=[{value:"name",name:"名称",sample:"Alex Chen"},{value:"firstName",name:"First name",sample:"Alex"},{value:"lastName",name:"Last name",sample:"Chen"},{value:"company",name:"公司",sample:"Acme Trading"},{value:"location",name:"所在地",sample:"Shanghai, China"},{value:"email",name:"邮箱",sample:"alex@example.com"},{value:"phone",name:"电话",sample:"+86 138 0000 0000"}];
const SAMPLE={orderNumber:"20260720-001",customerName:"Alex Chen",customerPhone:"+86 138 0000 0000",currency:"USD",total:"114.00",paymentSummary:"PayPal · US Sales",address:"Alex Chen · +86 138 0000 0000 · 88 Market Street, Shanghai",recipientName:"Alex Chen",recipientPhone:"+86 138 0000 0000",notes:"Handle with care"};

export function OrderTemplateEditor({format,request,onToken,onToast,onDirtyChange}:{format:TemplateFormat;request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onToast:(text:string)=>void;onDirtyChange:(dirty:boolean)=>void}){
  const fallback=format==="text"?DEFAULT_TEXT:DEFAULT_IMAGE;
  const [template,setTemplate]=useState<OrderTemplate>(fallback),[saved,setSaved]=useState(""),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[dragId,setDragId]=useState("");
  const serialized=JSON.stringify(template),dirty=Boolean(saved&&serialized!==saved),selected=template.blocks.find(block=>block.id===selectedId)??template.blocks[0];
  useEffect(()=>onDirtyChange(dirty),[dirty,onDirtyChange]);
  useEffect(()=>{const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before);},[dirty]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const result=await request("/api/v1/admin/order-templates");onToken(result.token);const body=await result.response.json() as Record<string,unknown>&{message?:string};if(!result.response.ok)throw new Error(body.message??`HTTP ${result.response.status}`);const key=format==="text"?"textTemplate":format==="image"?"imageTemplate":format==="pdf"?"pdfTemplate":`${format}Template`;const value=(body[key] as OrderTemplate|undefined)??fallback;setTemplate(value);setSaved(JSON.stringify(value));setSelectedId(value.blocks[0]?.id??"");}catch(reason){setError(reason instanceof Error?reason.message:"模板加载失败");}finally{setLoading(false);}},[format,request,onToken,fallback]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const change=(patch:Partial<Block>)=>setTemplate(value=>({...value,blocks:value.blocks.map(block=>block.id===selected?.id?{...block,...patch}:block)}));
  const move=(id:string,to:number)=>setTemplate(value=>{const from=value.blocks.findIndex(block=>block.id===id);if(from<0||to<0||to>=value.blocks.length||from===to)return value;const blocks=[...value.blocks],[block]=blocks.splice(from,1);blocks.splice(to,0,block);return{...value,blocks};});
  const add=(type:BlockType)=>{if(!META[type].repeatable&&template.blocks.some(block=>block.type===type))return;let suffix=1;while(template.blocks.some(block=>block.id===`${type}-${suffix}`))suffix++;const id=`${type}-${suffix}`,block:Block={id,type,label:defaultLabel(type),...(format==="text"?{blankAfter:true}:{fontSize:"medium",textColor:"#20372D",backgroundColor:"#FFFFFF",align:"left"}),...(type==="customText"?{text:"Thank you, {{customerName}}!"}:{}),...(type==="contactInfo"?{contactFields:CONTACT_FIELDS.map(field=>field.value)}:{}),...(type==="itemList"?{itemTemplate:DEFAULT_ITEM_TEMPLATE,...(format!=="text"?{showProductImages:true,imageSize:"medium" as const}:{})}:{})};setTemplate(value=>({...value,blocks:[...value.blocks,block]}));setSelectedId(id);};
  const remove=(block:Block)=>{if(META[block.type].required)return;setTemplate(value=>({...value,blocks:value.blocks.filter(item=>item.id!==block.id)}));setSelectedId(template.blocks.find(item=>item.id!==block.id)?.id??"");};
  async function save(){setSaving(true);setError("");try{const result=await request(`/api/v1/admin/order-templates/${format}`,{method:"PUT",headers:{"content-type":"application/json"},body:serialized});onToken(result.token);const body=await result.response.json().catch(()=>({})) as {message?:string;error?:string};if(!result.response.ok)throw new Error(body.message??body.error??`HTTP ${result.response.status}`);setSaved(serialized);onToast(`${format==="text"?"文字":format==="pdf"?"PDF":"图片"}订单模板已保存`);}catch(reason){setError(reason instanceof Error?reason.message:"模板保存失败");}finally{setSaving(false);}}
  if(loading)return <div className="template-loading"><RefreshCw className="spin" size={18}/>正在读取模板…</div>;
  return <div className="template-editor-wrap"><header className="template-editor-head"><div><h2>{format==="text"?"文字订单模板":"图片订单模板"}</h2><p>{format==="text"?"按 WhatsApp 文本能力配置强调样式。":"配置发送给客户的 PNG 订单版式。"}</p></div><span className={dirty?"dirty":""}>{dirty?"有未保存修改":"已保存"}</span><button className="secondary-action" onClick={()=>void load()} disabled={saving}><RefreshCw size={14}/>重新加载</button><button className="secondary-action" onClick={()=>{const value=structuredClone(fallback);setTemplate(value);setSelectedId(value.blocks[0].id);}} disabled={saving}><RotateCcw size={14}/>恢复默认</button><button className="primary-action" onClick={()=>void save()} disabled={!dirty||saving}>{saving?<RefreshCw className="spin" size={14}/>:<Check size={14}/>}保存模板</button></header>{error&&<span className="login-error template-error">{error}</span>}<div className="template-editor-grid"><aside className="template-palette"><h3>组件库</h3><p>点击添加到画布底部</p>{TYPES.map(type=>{const disabled=!META[type].repeatable&&template.blocks.some(block=>block.type===type);return <button key={type} disabled={disabled} onClick={()=>add(type)}><Plus size={13}/><span><b>{META[type].name}</b><small>{disabled?"已添加":META[type].description}</small></span></button>;})}</aside><section className="template-canvas"><header><h3>布局画布</h3><span>拖拽或使用箭头排序</span></header>{template.blocks.map((block,index)=><article key={block.id} draggable onDragStart={()=>setDragId(block.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>{move(dragId,index);setDragId("");}} className={`${selected?.id===block.id?"selected":""} ${dragId===block.id?"dragging":""}`} onClick={()=>setSelectedId(block.id)}><GripVertical size={16}/><span><b>{META[block.type].name}</b><small>{block.type==="customText"?block.text||"自定义文本":block.label||META[block.type].description}</small></span><div><button aria-label="上移" disabled={index===0} onClick={event=>{event.stopPropagation();move(block.id,index-1);}}><ArrowUp size={13}/></button><button aria-label="下移" disabled={index===template.blocks.length-1} onClick={event=>{event.stopPropagation();move(block.id,index+1);}}><ArrowDown size={13}/></button><button aria-label="删除" title={META[block.type].required?"核心组件不可删除":"删除组件"} disabled={META[block.type].required} onClick={event=>{event.stopPropagation();remove(block);}}><Trash2 size={13}/></button></div></article>)}</section><aside className="template-side">{selected&&<BlockProperties format={format} block={selected} onChange={change}/>}<TemplatePreview format={format} template={template}/></aside></div></div>;
}

function BlockProperties({format,block,onChange}:{format:TemplateFormat;block:Block;onChange:(patch:Partial<Block>)=>void}){
  return <section className="template-properties"><h3>组件属性</h3><b>{META[block.type].name}</b>
    {!["divider","customText"].includes(block.type)&&<label>标签文字<input value={block.label??""} maxLength={80} onChange={event=>onChange({label:event.target.value})}/></label>}
    {block.type==="orderHeader"&&<fieldset className="order-status-labels"><legend>不同订单状态的标题文字</legend><small>订单标题会按当前状态使用对应文字，再拼接订单编号。</small>{ORDER_STATUS_LABELS.map(item=><label key={item.value}><span>{item.name}</span><input value={block.statusLabels?.[item.value]??item.defaultLabel} maxLength={80} onChange={event=>onChange({statusLabels:{...DEFAULT_STATUS_LABELS,...block.statusLabels,[item.value]:event.target.value}})}/></label>)}</fieldset>}
    {block.type==="customText"&&<><label>文本内容<textarea value={block.text??""} maxLength={1000} onChange={event=>onChange({text:event.target.value})}/></label><small className="variable-help">可用变量：{"{{orderNumber}} {{customerName}} {{customerPhone}} {{currency}} {{total}} {{address}} {{notes}}"}</small></>}
    {block.type==="contactInfo"&&<fieldset className="template-checks"><legend>显示字段</legend>{CONTACT_FIELDS.map(field=><label key={field.value}><input type="checkbox" checked={(block.contactFields??CONTACT_FIELDS.map(item=>item.value)).includes(field.value)} onChange={event=>{const current=block.contactFields??CONTACT_FIELDS.map(item=>item.value),next=event.target.checked?[...current,field.value]:current.filter(value=>value!==field.value);if(next.length)onChange({contactFields:next});}}/>{field.name}</label>)}</fieldset>}
    {block.type==="itemList"&&<><label>Item 文本模板<input value={block.itemTemplate??DEFAULT_ITEM_TEMPLATE} maxLength={500} onChange={event=>onChange({itemTemplate:event.target.value})}/></label><small className="variable-help">可用变量：{"{{index}} {{title}} {{sku}} {{quantity}} {{price}} {{subtotal}}"}</small></>}
    {format==="text"?<div className="template-checks">{[["bold","粗体"],["italic","斜体"],["strikethrough","删除线"],["monospace","等宽"],["blankAfter","组件后空行"]].map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(block[key as keyof Block])} onChange={event=>onChange({[key]:event.target.checked})}/>{label}</label>)}</div>:<>
      <div className="template-property-row"><label>字号<select value={block.fontSize??"medium"} onChange={event=>onChange({fontSize:event.target.value as Block["fontSize"]})}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select></label><label>对齐<select value={block.align??"left"} onChange={event=>onChange({align:event.target.value as Block["align"]})}><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></label></div>
      <div className="template-property-row"><label>文字颜色<input type="color" value={block.textColor??"#20372D"} onChange={event=>onChange({textColor:event.target.value.toUpperCase()})}/></label><label>背景颜色<input type="color" value={block.backgroundColor??"#FFFFFF"} onChange={event=>onChange({backgroundColor:event.target.value.toUpperCase()})}/></label></div>
      {block.type==="itemList"&&<div className="template-checks"><label><input type="checkbox" checked={block.showProductImages!==false} onChange={event=>onChange({showProductImages:event.target.checked})}/>显示商品图片</label><label>图片尺寸<select value={block.imageSize??"medium"} onChange={event=>onChange({imageSize:event.target.value as Block["imageSize"]})}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select></label></div>}
    </>}
  </section>;
}

function TemplatePreview({format,template}:{format:TemplateFormat;template:OrderTemplate}){const blocks=useMemo(()=>previewBlocks(template),[template]);return <section className={`template-preview ${format}`}><header><h3>实时预览</h3><span>示例订单</span></header><div>{blocks.map(({block,lines})=><section key={block.id} style={format!=="text"?{color:block.textColor,background:block.backgroundColor,textAlign:block.align,fontSize:block.fontSize==="large"?"16px":block.fontSize==="small"?"10px":"12px"}:undefined} className={format==="text"?[block.bold&&"bold",block.italic&&"italic",block.strikethrough&&"strike",block.monospace&&"mono"].filter(Boolean).join(" "):""}>{lines.map((line,index)=><p key={index}>{line||"\u00a0"}</p>)}{format!=="text"&&block.type==="itemList"&&block.showProductImages!==false&&<span className={`sample-product-image ${block.imageSize??"medium"}`}>IMG</span>}</section>)}</div></section>}

function previewBlocks(template:OrderTemplate){const replace=(text:string)=>text.replace(/{{\s*([A-Za-z]+)\s*}}/g,(_,key:string)=>SAMPLE[key as keyof typeof SAMPLE]??"");return template.blocks.map(block=>{let lines:string[]=[];const label=block.label??defaultLabel(block.type);if(block.type==="orderHeader")lines=[`${block.statusLabels?.quotation?.trim()||label} #${SAMPLE.orderNumber}`];if(block.type==="itemList")lines=[...(label?[label]:[]),previewOrderItem(block.itemTemplate,{index:"1",title:"Premium perfume",sku:"PERFUME-001",quantity:"2",price:"USD 49.75",subtotal:"USD 99.50"}),previewOrderItem(block.itemTemplate,{index:"2",title:"Gift box",sku:"GIFT-001",quantity:"1",price:"USD 8.00",subtotal:"USD 8.00"})];if(block.type==="feeList")lines=[label,"Shipping - USD 6.50"];if(block.type==="total")lines=[`${label} USD ${SAMPLE.total}`];if(block.type==="paymentSummary")lines=[`${label} ${SAMPLE.paymentSummary}`];if(block.type==="shippingAddress")lines=[label,SAMPLE.address];if(block.type==="contactInfo"){const selected=block.contactFields??CONTACT_FIELDS.map(field=>field.value);lines=[...(label?[label]:[]),...CONTACT_FIELDS.filter(field=>selected.includes(field.value)).map(field=>`${field.name}: ${field.sample}`)];}if(block.type==="notes")lines=[`${label} ${SAMPLE.notes}`];if(block.type==="divider")lines=["────────────────"];if(block.type==="customText")lines=replace(block.text??"").split("\n");return{block,lines};});}
function previewOrderItem(template:string|undefined,variables:Record<string,string>){return(template?.trim()||DEFAULT_ITEM_TEMPLATE).replace(/{{\s*([A-Za-z]+)\s*}}/g,(_,key:string)=>variables[key]??"");}
function defaultLabel(type:BlockType){return({orderHeader:"Order",itemList:"Items:",feeList:"Additional fees:",total:"Total:",paymentSummary:"Payment:",shippingAddress:"Shipping address:",contactInfo:"Customer:",notes:"Notes:",divider:"",customText:""})[type];}
export const ORDER_TEMPLATE_DEFAULTS={text:DEFAULT_TEXT,image:DEFAULT_IMAGE,pdf:DEFAULT_IMAGE};
