"use client";

import { Check, LoaderCircle, Save, Truck } from "lucide-react";
import { useState } from "react";

type Tracking={carrier:string;trackingNumber:string;trackingUrl:string;paypalTrackingSyncedAt:string|null};
type Order={id:string;paymentProfile:{methodType:string}|null;paymentRequest:{status:string}|null;tracking:Tracking|null};

export function OrderTrackingPanel({order,token,onToken,onToast}:{order:Order;token:string;onToken:(token:string)=>void;onToast:(text:string)=>void}){
  const [tracking,setTracking]=useState<Tracking>(order.tracking??{carrier:"",trackingNumber:"",trackingUrl:"",paypalTrackingSyncedAt:null}),[busy,setBusy]=useState<"save"|"sync"|"">(""),[error,setError]=useState("");
  const paypalPaid=order.paymentProfile?.methodType==="paypal"&&["PAID","MARKED_AS_PAID","PAID_EXTERNAL"].includes(order.paymentRequest?.status.toUpperCase()??"");
  async function request(path:string,method:"PATCH"|"POST",body?:unknown){const result=await fetch(`/api/v1/orders/${order.id}${path}`,{method,headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await result.json().catch(()=>({})) as Record<string,unknown>;if(!result.ok)throw new Error(String(data.message??data.error??`HTTP ${result.status}`));return data;}
  async function save(){setBusy("save");setError("");try{const saved=await request("/tracking","PATCH",tracking);setTracking({carrier:String(saved.carrier??tracking.carrier),trackingNumber:String(saved.trackingNumber??tracking.trackingNumber),trackingUrl:String(saved.trackingUrl??tracking.trackingUrl),paypalTrackingSyncedAt:null});onToast("物流信息已保存");}catch(reason){setError(reason instanceof Error?reason.message:"物流信息保存失败");}finally{setBusy("");}}
  async function sync(){setBusy("sync");setError("");try{const saved=await request("/tracking/sync-paypal","POST");setTracking(value=>({...value,paypalTrackingSyncedAt:String(saved.syncedAt??new Date().toISOString())}));onToast("物流信息已同步到 PayPal");}catch(reason){setError(reason instanceof Error?reason.message:"PayPal 同步失败");}finally{setBusy("");}}
  return <section className="payment-request-panel"><header><span><Truck size={17}/><span><b>物流跟踪</b><small>{tracking.paypalTrackingSyncedAt?"已同步到 PayPal":"保存后可同步到符合条件的 PayPal 已付款订单"}</small></span></span></header><div className="product-form-grid"><label>承运商<input value={tracking.carrier} maxLength={80} placeholder="例如 DHL、FEDEX、UPS" onChange={event=>setTracking(value=>({...value,carrier:event.target.value}))}/></label><label>物流单号<input value={tracking.trackingNumber} maxLength={160} placeholder="输入追踪号码" onChange={event=>setTracking(value=>({...value,trackingNumber:event.target.value}))}/></label></div><label>查询链接（可选）<input type="url" value={tracking.trackingUrl} maxLength={2000} placeholder="https://..." onChange={event=>setTracking(value=>({...value,trackingUrl:event.target.value}))}/></label><div className="payment-request-actions"><button className="secondary-action" onClick={()=>void save()} disabled={Boolean(busy)||!tracking.carrier.trim()||!tracking.trackingNumber.trim()}><Save size={14}/>{busy==="save"?"正在保存…":"保存物流信息"}</button>{paypalPaid&&<button className="primary-action" onClick={()=>void sync()} disabled={Boolean(busy)||!tracking.carrier.trim()||!tracking.trackingNumber.trim()}>{busy==="sync"?<LoaderCircle className="spin" size={14}/>:<Check size={14}/>} {busy==="sync"?"正在同步…":"同步到 PayPal"}</button>}</div>{!paypalPaid&&order.paymentProfile?.methodType==="paypal"&&<small>PayPal 发票需先显示“已付款”才可同步。</small>}{error&&<span className="login-error">{error}</span>}</section>;
}
