"use client";

import { ArrowDown, ArrowUp, Check, GripVertical, Plus, RefreshCw, RotateCcw, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

export type TemplateFormat="text"|"image";
type BlockType="orderHeader"|"itemList"|"feeList"|"total"|"shippingAddress"|"notes"|"divider"|"customText";
type Block={id:string;type:BlockType;label?:string;text?:string;bold?:boolean;italic?:boolean;strikethrough?:boolean;monospace?:boolean;blankAfter?:boolean;fontSize?:"small"|"medium"|"large";textColor?:string;backgroundColor?:string;align?:"left"|"center"|"right";showProductImages?:boolean;imageSize?:"small"|"medium"|"large"};
export type OrderTemplate={version:1;blocks:Block[]};
type RequestResult={response:Response;token:string};

const META:Record<BlockType,{name:string;description:string;repeatable?:boolean;required?:boolean}>={
  orderHeader:{name:"订单标题 / 编号",description:"显示订单标题和订单号"},itemList:{name:"商品列表",description:"自动重复订单商品",required:true},feeList:{name:"附加费用",description:"没有费用时自动隐藏"},total:{name:"订单总计",description:"显示计算后的总金额",required:true},shippingAddress:{name:"收货地址",description:"没有地址时自动隐藏"},notes:{name:"订单备注",description:"没有备注时自动隐藏"},divider:{name:"分隔线",description:"分隔相邻内容",repeatable:true},customText:{name:"自定义文本",description:"支持插入订单变量",repeatable:true},
};
const TYPES=Object.keys(META) as BlockType[];
const DEFAULT_TEXT:OrderTemplate={version:1,blocks:[{id:"order-header",type:"orderHeader",label:"Order",bold:true,blankAfter:true},{id:"items",type:"itemList",label:"Items:",blankAfter:true},{id:"fees",type:"feeList",label:"Additional fees:",blankAfter:true},{id:"total",type:"total",label:"Total:",bold:true},{id:"notes",type:"notes",label:"Notes:"}]};
const DEFAULT_IMAGE:OrderTemplate={version:1,blocks:[{id:"order-header",type:"orderHeader",label:"Order",fontSize:"large",textColor:"#FFFFFF",backgroundColor:"#153F2F",align:"left"},{id:"items",type:"itemList",label:"Items:",fontSize:"medium",textColor:"#20372D",backgroundColor:"#F6F9F7",align:"left",showProductImages:true,imageSize:"medium"},{id:"fees",type:"feeList",label:"Additional fees:",fontSize:"small",textColor:"#20372D",backgroundColor:"#FAFCFB",align:"left"},{id:"total",type:"total",label:"Total:",fontSize:"large",textColor:"#FFFFFF",backgroundColor:"#153F2F",align:"left"},{id:"notes",type:"notes",label:"Notes:",fontSize:"small",textColor:"#20372D",backgroundColor:"#FFFAF0",align:"left"}]};
const SAMPLE={orderNumber:"20260720-001",customerName:"Alex Chen",customerPhone:"+86 138 0000 0000",currency:"USD",total:"114.00",address:"Alex Chen · +86 138 0000 0000 · 88 Market Street, Shanghai",recipientName:"Alex Chen",recipientPhone:"+86 138 0000 0000",notes:"Handle with care"};

export function OrderTemplateEditor({format,request,onToken,onToast,onDirtyChange}:{format:TemplateFormat;request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onToast:(text:string)=>void;onDirtyChange:(dirty:boolean)=>void}){
  const fallback=format==="text"?DEFAULT_TEXT:DEFAULT_IMAGE;
  const [template,setTemplate]=useState<OrderTemplate>(fallback),[saved,setSaved]=useState(""),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[dragId,setDragId]=useState("");
  const serialized=JSON.stringify(template),dirty=Boolean(saved&&serialized!==saved),selected=template.blocks.find(block=>block.id===selectedId)??template.blocks[0];
  useEffect(()=>onDirtyChange(dirty),[dirty,onDirtyChange]);
  useEffect(()=>{const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before);},[dirty]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const result=await request("/api/v1/admin/order-templates");onToken(result.token);const body=await result.response.json() as {textTemplate?:OrderTemplate;imageTemplate?:OrderTemplate;message?:string};if(!result.response.ok)throw new Error(body.message??`HTTP ${result.response.status}`);const value=(format==="text"?body.textTemplate:body.imageTemplate)??fallback;setTemplate(value);setSaved(JSON.stringify(value));setSelectedId(value.blocks[0]?.id??"");}catch(reason){setError(reason instanceof Error?reason.message:"模板加载失败");}finally{setLoading(false);}},[format,request,onToken,fallback]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const change=(patch:Partial<Block>)=>setTemplate(value=>({...value,blocks:value.blocks.map(block=>block.id===selected?.id?{...block,...patch}:block)}));
  const move=(id:string,to:number)=>setTemplate(value=>{const from=value.blocks.findIndex(block=>block.id===id);if(from<0||to<0||to>=value.blocks.length||from===to)return value;const blocks=[...value.blocks],[block]=blocks.splice(from,1);blocks.splice(to,0,block);return{...value,blocks};});
  const add=(type:BlockType)=>{if(!META[type].repeatable&&template.blocks.some(block=>block.type===type))return;let suffix=1;while(template.blocks.some(block=>block.id===`${type}-${suffix}`))suffix++;const id=`${type}-${suffix}`,block:Block={id,type,label:defaultLabel(type),...(format==="text"?{blankAfter:true}:{fontSize:"medium",textColor:"#20372D",backgroundColor:"#FFFFFF",align:"left"}),...(type==="customText"?{text:"Thank you, {{customerName}}!"}:{}),...(type==="itemList"&&format==="image"?{showProductImages:true,imageSize:"medium"}:{})};setTemplate(value=>({...value,blocks:[...value.blocks,block]}));setSelectedId(id);};
  const remove=(block:Block)=>{if(META[block.type].required)return;setTemplate(value=>({...value,blocks:value.blocks.filter(item=>item.id!==block.id)}));setSelectedId(template.blocks.find(item=>item.id!==block.id)?.id??"");};
  async function save(){setSaving(true);setError("");try{const result=await request(`/api/v1/admin/order-templates/${format}`,{method:"PUT",headers:{"content-type":"application/json"},body:serialized});onToken(result.token);const body=await result.response.json().catch(()=>({})) as {message?:string;error?:string};if(!result.response.ok)throw new Error(body.message??body.error??`HTTP ${result.response.status}`);setSaved(serialized);onToast(`${format==="text"?"文字":"图片"}订单模板已保存`);}catch(reason){setError(reason instanceof Error?reason.message:"模板保存失败");}finally{setSaving(false);}}
  if(loading)return <div className="template-loading"><RefreshCw className="spin" size={18}/>正在读取模板…</div>;
  return <div className="template-editor-wrap"><header className="template-editor-head"><div><h2>{format==="text"?"文字订单模板":"图片订单模板"}</h2><p>{format==="text"?"按 WhatsApp 文本能力配置强调样式。":"配置发送给客户的 PNG 订单版式。"}</p></div><span className={dirty?"dirty":""}>{dirty?"有未保存修改":"已保存"}</span><button className="secondary-action" onClick={()=>void load()} disabled={saving}><RefreshCw size={14}/>重新加载</button><button className="secondary-action" onClick={()=>{const value=structuredClone(fallback);setTemplate(value);setSelectedId(value.blocks[0].id);}} disabled={saving}><RotateCcw size={14}/>恢复默认</button><button className="primary-action" onClick={()=>void save()} disabled={!dirty||saving}>{saving?<RefreshCw className="spin" size={14}/>:<Check size={14}/>}保存模板</button></header>{error&&<span className="login-error template-error">{error}</span>}<div className="template-editor-grid"><aside className="template-palette"><h3>组件库</h3><p>点击添加到画布底部</p>{TYPES.map(type=>{const disabled=!META[type].repeatable&&template.blocks.some(block=>block.type===type);return <button key={type} disabled={disabled} onClick={()=>add(type)}><Plus size={13}/><span><b>{META[type].name}</b><small>{disabled?"已添加":META[type].description}</small></span></button>;})}</aside><section className="template-canvas"><header><h3>布局画布</h3><span>拖拽或使用箭头排序</span></header>{template.blocks.map((block,index)=><article key={block.id} draggable onDragStart={()=>setDragId(block.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>{move(dragId,index);setDragId("");}} className={`${selected?.id===block.id?"selected":""} ${dragId===block.id?"dragging":""}`} onClick={()=>setSelectedId(block.id)}><GripVertical size={16}/><span><b>{META[block.type].name}</b><small>{block.type==="customText"?block.text||"自定义文本":block.label||META[block.type].description}</small></span><div><button aria-label="上移" disabled={index===0} onClick={event=>{event.stopPropagation();move(block.id,index-1);}}><ArrowUp size={13}/></button><button aria-label="下移" disabled={index===template.blocks.length-1} onClick={event=>{event.stopPropagation();move(block.id,index+1);}}><ArrowDown size={13}/></button><button aria-label="删除" title={META[block.type].required?"核心组件不可删除":"删除组件"} disabled={META[block.type].required} onClick={event=>{event.stopPropagation();remove(block);}}><Trash2 size={13}/></button></div></article>)}</section><aside className="template-side">{selected&&<BlockProperties format={format} block={selected} onChange={change}/>}<TemplatePreview format={format} template={template}/></aside></div></div>;
}

function BlockProperties({format,block,onChange}:{format:TemplateFormat;block:Block;onChange:(patch:Partial<Block>)=>void}){
  return <section className="template-properties"><h3>组件属性</h3><b>{META[block.type].name}</b>
    {!["divider","customText"].includes(block.type)&&<label>标签文字<input value={block.label??""} maxLength={80} onChange={event=>onChange({label:event.target.value})}/></label>}
    {block.type==="customText"&&<><label>文本内容<textarea value={block.text??""} maxLength={1000} onChange={event=>onChange({text:event.target.value})}/></label><small className="variable-help">可用变量：{"{{orderNumber}} {{customerName}} {{customerPhone}} {{currency}} {{total}} {{address}} {{notes}}"}</small></>}
    {format==="text"?<div className="template-checks">{[["bold","粗体"],["italic","斜体"],["strikethrough","删除线"],["monospace","等宽"],["blankAfter","组件后空行"]].map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(block[key as keyof Block])} onChange={event=>onChange({[key]:event.target.checked})}/>{label}</label>)}</div>:<>
      <div className="template-property-row"><label>字号<select value={block.fontSize??"medium"} onChange={event=>onChange({fontSize:event.target.value as Block["fontSize"]})}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select></label><label>对齐<select value={block.align??"left"} onChange={event=>onChange({align:event.target.value as Block["align"]})}><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></label></div>
      <div className="template-property-row"><label>文字颜色<input type="color" value={block.textColor??"#20372D"} onChange={event=>onChange({textColor:event.target.value.toUpperCase()})}/></label><label>背景颜色<input type="color" value={block.backgroundColor??"#FFFFFF"} onChange={event=>onChange({backgroundColor:event.target.value.toUpperCase()})}/></label></div>
      {block.type==="itemList"&&<div className="template-checks"><label><input type="checkbox" checked={block.showProductImages!==false} onChange={event=>onChange({showProductImages:event.target.checked})}/>显示商品图片</label><label>图片尺寸<select value={block.imageSize??"medium"} onChange={event=>onChange({imageSize:event.target.value as Block["imageSize"]})}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select></label></div>}
    </>}
  </section>;
}

function TemplatePreview({format,template}:{format:TemplateFormat;template:OrderTemplate}){const blocks=useMemo(()=>previewBlocks(template),[template]);return <section className={`template-preview ${format}`}><header><h3>实时预览</h3><span>示例订单</span></header><div>{blocks.map(({block,lines})=><section key={block.id} style={format==="image"?{color:block.textColor,background:block.backgroundColor,textAlign:block.align,fontSize:block.fontSize==="large"?"16px":block.fontSize==="small"?"10px":"12px"}:undefined} className={format==="text"?[block.bold&&"bold",block.italic&&"italic",block.strikethrough&&"strike",block.monospace&&"mono"].filter(Boolean).join(" "):""}>{lines.map((line,index)=><p key={index}>{line||"\u00a0"}</p>)}{format==="image"&&block.type==="itemList"&&block.showProductImages!==false&&<span className={`sample-product-image ${block.imageSize??"medium"}`}>IMG</span>}</section>)}</div></section>}

function previewBlocks(template:OrderTemplate){const replace=(text:string)=>text.replace(/{{\s*([A-Za-z]+)\s*}}/g,(_,key:string)=>SAMPLE[key as keyof typeof SAMPLE]??"");return template.blocks.map(block=>{let lines:string[]=[];const label=block.label??defaultLabel(block.type);if(block.type==="orderHeader")lines=[`${label} #${SAMPLE.orderNumber}`];if(block.type==="itemList")lines=[label,"1. Premium perfume x 2 - USD 49.75 each - USD 99.50","2. Gift box x 1 - USD 8.00 each - USD 8.00"];if(block.type==="feeList")lines=[label,"Shipping - USD 6.50"];if(block.type==="total")lines=[`${label} USD ${SAMPLE.total}`];if(block.type==="shippingAddress")lines=[label,SAMPLE.address];if(block.type==="notes")lines=[`${label} ${SAMPLE.notes}`];if(block.type==="divider")lines=["────────────────"];if(block.type==="customText")lines=replace(block.text??"").split("\n");return{block,lines};});}
function defaultLabel(type:BlockType){return({orderHeader:"Order",itemList:"Items:",feeList:"Additional fees:",total:"Total:",shippingAddress:"Shipping address:",notes:"Notes:",divider:"",customText:""})[type];}
export const ORDER_TEMPLATE_DEFAULTS={text:DEFAULT_TEXT,image:DEFAULT_IMAGE};
