"use client";

import { ArrowDown, ArrowUp, Check, GripVertical, Plus, RefreshCw, RotateCcw, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

type BlockType="productImage"|"productName"|"sku"|"priceTiers"|"tags"|"divider"|"customText";
type Block={id:string;type:BlockType;label?:string;text?:string;fontSize?:"small"|"medium"|"large";textColor?:string;backgroundColor?:string;align?:"left"|"center"|"right";imageSize?:"small"|"medium"|"large";imageFit?:"cover"|"contain";showPlaceholder?:boolean};
export type ProductCardTemplate={version:1;blocks:Block[]};
type RequestResult={response:Response;token:string};
const META:Record<BlockType,{name:string;description:string;repeatable?:boolean;required?:boolean}>={
  productImage:{name:"产品图片",description:"展示产品主图或占位内容"},productName:{name:"产品名称",description:"显示产品名称",required:true},sku:{name:"SKU",description:"显示唯一 SKU",required:true},priceTiers:{name:"阶梯价格",description:"无价模式会自动隐藏",required:true},tags:{name:"产品标签",description:"没有标签时自动隐藏"},divider:{name:"分隔线",description:"分隔相邻内容",repeatable:true},customText:{name:"自定义文本",description:"支持产品变量",repeatable:true},
};
const TYPES=Object.keys(META) as BlockType[];
export const DEFAULT_PRODUCT_CARD_TEMPLATE:ProductCardTemplate={version:1,blocks:[{id:"image",type:"productImage",imageSize:"large",imageFit:"cover",showPlaceholder:true,backgroundColor:"#F2F6F4"},{id:"name",type:"productName",label:"Product",fontSize:"large",textColor:"#153F2F",backgroundColor:"#FFFFFF",align:"left"},{id:"sku",type:"sku",label:"SKU",fontSize:"small",textColor:"#607168",backgroundColor:"#FFFFFF",align:"left"},{id:"prices",type:"priceTiers",label:"Pricing",fontSize:"medium",textColor:"#20372D",backgroundColor:"#F2F8F5",align:"left"},{id:"tags",type:"tags",label:"",fontSize:"small",textColor:"#31644D",backgroundColor:"#EAF7F0",align:"left"}]};

export function ProductCardTemplateEditor({request,onToken,onToast,onDirtyChange}:{request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onToast:(text:string)=>void;onDirtyChange:(dirty:boolean)=>void}){
  const [template,setTemplate]=useState<ProductCardTemplate>(DEFAULT_PRODUCT_CARD_TEMPLATE),[saved,setSaved]=useState(""),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[dragId,setDragId]=useState("");
  const serialized=JSON.stringify(template),dirty=Boolean(saved&&saved!==serialized),selected=template.blocks.find(block=>block.id===selectedId)??template.blocks[0];
  useEffect(()=>onDirtyChange(dirty),[dirty,onDirtyChange]);
  useEffect(()=>{const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before);},[dirty]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const result=await request("/api/v1/admin/product-card-template");onToken(result.token);const body=await result.response.json() as {template?:ProductCardTemplate;message?:string};if(!result.response.ok)throw new Error(body.message??`HTTP ${result.response.status}`);const value=body.template??DEFAULT_PRODUCT_CARD_TEMPLATE;setTemplate(value);setSaved(JSON.stringify(value));setSelectedId(value.blocks[0]?.id??"");}catch(reason){setError(reason instanceof Error?reason.message:"模板加载失败");}finally{setLoading(false);}},[request,onToken]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const change=(patch:Partial<Block>)=>setTemplate(value=>({...value,blocks:value.blocks.map(block=>block.id===selected?.id?{...block,...patch}:block)}));
  const move=(id:string,to:number)=>setTemplate(value=>{const from=value.blocks.findIndex(block=>block.id===id);if(from<0||to<0||to>=value.blocks.length||from===to)return value;const blocks=[...value.blocks],[block]=blocks.splice(from,1);blocks.splice(to,0,block);return{...value,blocks};});
  function add(type:BlockType){if(!META[type].repeatable&&template.blocks.some(block=>block.type===type))return;let suffix=1;while(template.blocks.some(block=>block.id===`${type}-${suffix}`))suffix++;const id=`${type}-${suffix}`,block:Block={id,type,label:defaultLabel(type),fontSize:"medium",textColor:"#20372D",backgroundColor:"#FFFFFF",align:"left",...(type==="productImage"?{imageSize:"large" as const,imageFit:"cover" as const,showPlaceholder:true}:{}) ,...(type==="customText"?{text:"Contact us about {{name}} ({{sku}})"}:{})};setTemplate(value=>({...value,blocks:[...value.blocks,block]}));setSelectedId(id);}
  function remove(block:Block){if(META[block.type].required)return;setTemplate(value=>({...value,blocks:value.blocks.filter(item=>item.id!==block.id)}));setSelectedId(template.blocks.find(item=>item.id!==block.id)?.id??"");}
  async function save(){setSaving(true);setError("");try{const result=await request("/api/v1/admin/product-card-template",{method:"PUT",headers:{"content-type":"application/json"},body:serialized});onToken(result.token);const body=await result.response.json().catch(()=>({})) as {message?:string;error?:string};if(!result.response.ok)throw new Error(body.message??body.error??`HTTP ${result.response.status}`);setSaved(serialized);onToast("产品卡片模板已保存");}catch(reason){setError(reason instanceof Error?reason.message:"模板保存失败");}finally{setSaving(false);}}
  if(loading)return <div className="template-loading"><RefreshCw className="spin" size={18}/>正在读取产品卡片模板…</div>;
  return <div className="template-editor-wrap"><header className="template-editor-head"><div><h2>产品卡片模板</h2><p>配置发送给客户的产品 PNG 卡片；无价发送会隐藏价格组件。</p></div><span className={dirty?"dirty":""}>{dirty?"有未保存修改":"已保存"}</span><button className="secondary-action" onClick={()=>void load()} disabled={saving}><RefreshCw size={14}/>重新加载</button><button className="secondary-action" onClick={()=>{const value=structuredClone(DEFAULT_PRODUCT_CARD_TEMPLATE);setTemplate(value);setSelectedId(value.blocks[0].id);}} disabled={saving}><RotateCcw size={14}/>恢复默认</button><button className="primary-action" onClick={()=>void save()} disabled={!dirty||saving}>{saving?<RefreshCw className="spin" size={14}/>:<Check size={14}/>}保存模板</button></header>{error&&<span className="login-error template-error">{error}</span>}<div className="template-editor-grid"><aside className="template-palette"><h3>组件库</h3><p>点击添加到画布底部</p>{TYPES.map(type=>{const disabled=!META[type].repeatable&&template.blocks.some(block=>block.type===type);return <button key={type} disabled={disabled} onClick={()=>add(type)}><Plus size={13}/><span><b>{META[type].name}</b><small>{disabled?"已添加":META[type].description}</small></span></button>;})}</aside><section className="template-canvas"><header><h3>布局画布</h3><span>拖拽或使用箭头排序</span></header>{template.blocks.map((block,index)=><article key={block.id} draggable onDragStart={()=>setDragId(block.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>{move(dragId,index);setDragId("");}} className={`${selected?.id===block.id?"selected":""} ${dragId===block.id?"dragging":""}`} onClick={()=>setSelectedId(block.id)}><GripVertical size={16}/><span><b>{META[block.type].name}</b><small>{block.type==="customText"?block.text||"自定义文本":block.label||META[block.type].description}</small></span><div><button aria-label="上移" disabled={index===0} onClick={event=>{event.stopPropagation();move(block.id,index-1);}}><ArrowUp size={13}/></button><button aria-label="下移" disabled={index===template.blocks.length-1} onClick={event=>{event.stopPropagation();move(block.id,index+1);}}><ArrowDown size={13}/></button><button aria-label="删除" disabled={META[block.type].required} onClick={event=>{event.stopPropagation();remove(block);}}><Trash2 size={13}/></button></div></article>)}</section><aside className="template-side">{selected&&<Properties block={selected} onChange={change}/>}<Preview template={template}/></aside></div></div>;
}

function Properties({block,onChange}:{block:Block;onChange:(patch:Partial<Block>)=>void}){return <section className="template-properties"><h3>组件属性</h3><b>{META[block.type].name}</b>{!["productImage","divider","customText"].includes(block.type)&&<label>标签文字<input value={block.label??""} maxLength={80} onChange={event=>onChange({label:event.target.value})}/></label>}{block.type==="customText"&&<><label>文本内容<textarea value={block.text??""} maxLength={1000} onChange={event=>onChange({text:event.target.value})}/></label><small className="variable-help">可用变量：{"{{name}} {{sku}} {{currency}}"}</small></>}{block.type==="productImage"?<><div className="template-property-row"><label>图片尺寸<select value={block.imageSize??"large"} onChange={event=>onChange({imageSize:event.target.value as Block["imageSize"]})}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select></label><label>裁切方式<select value={block.imageFit??"cover"} onChange={event=>onChange({imageFit:event.target.value as Block["imageFit"]})}><option value="cover">铺满裁切</option><option value="contain">完整显示</option></select></label></div><div className="template-checks"><label><input type="checkbox" checked={block.showPlaceholder!==false} onChange={event=>onChange({showPlaceholder:event.target.checked})}/>无图片时显示占位</label></div></>:block.type!=="divider"&&<><div className="template-property-row"><label>字号<select value={block.fontSize??"medium"} onChange={event=>onChange({fontSize:event.target.value as Block["fontSize"]})}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select></label><label>对齐<select value={block.align??"left"} onChange={event=>onChange({align:event.target.value as Block["align"]})}><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></label></div><div className="template-property-row"><label>文字颜色<input type="color" value={block.textColor??"#20372D"} onChange={event=>onChange({textColor:event.target.value.toUpperCase()})}/></label><label>背景颜色<input type="color" value={block.backgroundColor??"#FFFFFF"} onChange={event=>onChange({backgroundColor:event.target.value.toUpperCase()})}/></label></div></>}</section>;}

function Preview({template}:{template:ProductCardTemplate}){const rows=useMemo(()=>template.blocks.map(block=>({block,lines:previewLines(block)})),[template]);return <section className="template-preview image"><header><h3>实时预览</h3><span>示例产品</span></header><div>{rows.map(({block,lines})=><section key={block.id} style={{color:block.textColor,background:block.backgroundColor,textAlign:block.align,fontSize:block.fontSize==="large"?"16px":block.fontSize==="small"?"10px":"12px"}}>{block.type==="productImage"?<span className={`product-card-template-image ${block.imageSize??"large"}`}>PRODUCT IMAGE</span>:lines.map((line,index)=><p key={index}>{line||"\u00a0"}</p>)}</section>)}</div></section>;}
function previewLines(block:Block){if(block.type==="productName")return[`${block.label?`${block.label}: `:""}Premium perfume`];if(block.type==="sku")return[`${block.label?`${block.label}: `:""}PERFUME-001`];if(block.type==="priceTiers")return[...(block.label?[block.label]:[]),"1+ USD 49.75 / unit","10+ units · USD 42.00 / unit"];if(block.type==="tags")return["Featured · Gift"];if(block.type==="divider")return["────────────────"];if(block.type==="customText")return[(block.text??"").replace("{{name}}","Premium perfume").replace("{{sku}}","PERFUME-001").replace("{{currency}}","USD")];return[];}
function defaultLabel(type:BlockType){return({productImage:"",productName:"Product",sku:"SKU",priceTiers:"Pricing",tags:"",divider:"",customText:""})[type];}
