"use client";

import { Download, FileText, UploadCloud, X } from "lucide-react";
import { useRef, useState } from "react";
import { parseCsv } from "./csv-transfer";

type RequestResult={response:Response;token:string};
type ImportTier={minQuantity:number;unitAmount:number;costAmount?:number;profitMargin?:number};
type ImportVariant={attributes:Record<string,string>;sku:string;priceTiers:ImportTier[];imageFileName?:string;imageMediaId?:string|null};
type ImportProduct={clientProductId:string;sku:string;name:string;description?:string;category?:string;brand?:string;currency?:string;weightAmount?:number;weightUnit?:"g"|"kg"|"oz"|"lbs";shippingClassId?:string|null;imageFileName?:string;imageMediaId?:string;galleryFileNames?:string[];galleryMediaIds?:string[];supplierLinks?:Array<{label:string;url:string;supplyPrice?:number}>;internalNote?:string;priceTiers?:ImportTier[];variants?:ImportVariant[];tags?:Array<{name:string;color:string}>};
type PreviewRow={line:number;sku:string;name:string;description:string;currency:string;price:string;tiers:string;tags:string;image:string;error:string};
const HEADER_ALIASES:Record<string,string>={sku:"sku","产品编号":"sku","产品sku":"sku",name:"name","名称":"name","产品名称":"name",description:"description","产品描述":"description","描述":"description",category:"category","分类":"category",brand:"brand","品牌":"brand",currency:"currency","币种":"currency",price:"price","unit_price":"price","单价":"price","默认单价":"price",price_tiers:"tiers","价格阶梯":"tiers","阶梯价格":"tiers",weight_amount:"weightAmount","重量":"weightAmount",weight_unit:"weightUnit","重量单位":"weightUnit",shipping_class:"shippingClass","shipping class":"shippingClass","运费类别":"shippingClass",tags:"tags","标签":"tags",image:"image",image_file:"image",image_filename:"image","图片":"image","图片文件名":"image",gallery_images:"galleryImages","产品相册":"galleryImages",variants:"variants","产品变体":"variants",supplier_links:"supplierLinks","供应商链接":"supplierLinks",internal_note:"internalNote","内部备注":"internalNote"};
const TAG_COLORS=["#E8EEF7","#E8F7EE","#FFF1D6","#F7E8EF","#EEE8F7"];

function buildPreview(text:string,currencies:string[],shippingClasses:Array<{id:string;name:string}>,imageNames:Set<string>):{rows:PreviewRow[];products:ImportProduct[];fatal:string}{
  const data=parseCsv(text);if(!data.length)return{rows:[],products:[],fatal:"CSV 文件为空"};
  const headers=data[0].map(value=>HEADER_ALIASES[value.trim().toLocaleLowerCase()]??"");
  for(const required of ["sku","name","currency"])if(!headers.includes(required))return{rows:[],products:[],fatal:`缺少必填列：${required}`};
  if(!headers.includes("price")&&!headers.includes("tiers"))return{rows:[],products:[],fatal:"需要 price（单价）或 price_tiers（阶梯价格）列"};
  const index=(name:string)=>headers.indexOf(name),seen=new Set<string>(),products:ImportProduct[]=[],rows:PreviewRow[]=[],moneyPattern=/^\d+(?:\.\d{1,2})?$/;
  for(const [offset,values] of data.slice(1).entries()){
    const value=(name:string)=>String(values[index(name)]??"").trim(),sku=value("sku"),name=value("name"),description=value("description"),category=value("category"),brand=value("brand"),currency=value("currency").toUpperCase(),price=value("price"),tierText=value("tiers"),weightAmount=value("weightAmount"),weightUnit=value("weightUnit").toLowerCase(),shippingClass=value("shippingClass"),shippingClassId=shippingClasses.find(item=>item.name.toLocaleLowerCase()===shippingClass.toLocaleLowerCase())?.id,tagText=value("tags"),image=value("image"),galleryText=value("galleryImages"),variantsText=value("variants"),supplierText=value("supplierLinks"),internalNote=value("internalNote"),tierParts=tierText?tierText.split(/[|；;]/).filter(Boolean):[];
    let tiers:ImportTier[]=[];let tierSyntaxValid=true;try{tiers=tierText.trim().startsWith("[")?JSON.parse(tierText):tierText?tierParts.map(item=>{const parts=item.trim().split(/[:：]/);return{minQuantity:Number(parts[0]),unitAmount:Number(parts[1])};}):[{minQuantity:1,unitAmount:Number(price)}];if(!Array.isArray(tiers))throw new Error();}catch{tierSyntaxValid=false;}const updateOnly=!currency&&!price&&!tierText;
    let error="";
    if(!sku||sku.length>80)error="SKU 必填且不能超过 80 个字符";else if(seen.has(sku.toLocaleLowerCase()))error="CSV 中 SKU 重复";else if(!name||name.length>120)error="产品名称必填且不能超过 120 个字符";else if(description.length>2000)error="产品描述不能超过 2000 个字符";else if(category.length>80||brand.length>80)error="分类和品牌不能超过 80 个字符";else if(Boolean(weightAmount)!==Boolean(weightUnit)||Boolean(weightAmount)&&(!(Number(weightAmount)>0)||!["g","kg","oz","lbs"].includes(weightUnit)))error="重量与单位需同时填写，单位支持 g、kg、oz、lbs";else if(shippingClass&&!shippingClassId)error=`Shipping class 不存在：${shippingClass}`;else if(!updateOnly&&!currencies.includes(currency))error=`币种 ${currency||"（空）"} 未启用`;else if(!updateOnly&&((!tierText&&!moneyPattern.test(price))||(tierText&&!tierSyntaxValid)||!tiers.length||tiers.some((tier,tierIndex)=>tier.minQuantity<1||(tierIndex===0?tier.minQuantity!==1:tier.minQuantity<=tiers[tierIndex-1].minQuantity))))error="价格格式错误；阶梯价格示例：1:99.00|10:89.00";else if(image&&!imageNames.has(image.toLocaleLowerCase()))error=`未选择图片文件：${image}`;
    let tags:Array<{name:string;color:string}>=[];try{tags=tagText.trim().startsWith("[")?JSON.parse(tagText):tagText.split(/[|；;]/).map(item=>item.trim()).filter(Boolean).map((tag,tagIndex)=>({name:tag,color:TAG_COLORS[tagIndex%TAG_COLORS.length]}));if(!Array.isArray(tags)||tags.some(tag=>!tag||typeof tag!=="object"))throw new Error();}catch{error=error||"tags 必须是有效 JSON 或以 | 分隔的标签";}if(tags.some(tag=>typeof tag.name!=="string"||tag.name.length>40||typeof tag.color!=="string"||!/^#[0-9A-Fa-f]{6}$/.test(tag.color))||tags.length>30)error=error||"标签不能超过 30 个，每个最多 40 个字符且颜色需为 #RRGGBB";
    let variants:ImportVariant[]|undefined,supplierLinks:ImportProduct["supplierLinks"]|undefined,galleryFileNames=headers.includes("galleryImages")?galleryText.split(/[|；;]/).map(item=>item.trim()).filter(Boolean):undefined;try{if(variantsText)variants=JSON.parse(variantsText);if(supplierText)supplierLinks=JSON.parse(supplierText);if(variants&&(!Array.isArray(variants)||variants.some(item=>!item||typeof item!=="object")))throw new Error();if(supplierLinks&&(!Array.isArray(supplierLinks)||supplierLinks.some(item=>!item||typeof item!=="object")))throw new Error();}catch{variants=undefined;supplierLinks=undefined;error=error||"variants 或 supplier_links 必须是有效 JSON";}
    const allImages=[image,...(galleryFileNames??[]),...(variants??[]).map(item=>item.imageFileName??"")].filter(Boolean);if(allImages.some(item=>!imageNames.has(item.toLocaleLowerCase())))error=error||`未选择图片文件：${allImages.find(item=>!imageNames.has(item.toLocaleLowerCase()))}`;
    seen.add(sku.toLocaleLowerCase());const preview={line:offset+2,sku,name,description,currency,price,tiers:tierText,tags:tagText,image,error};rows.push(preview);if(!error)products.push(updateOnly?{clientProductId:crypto.randomUUID(),sku,name,description:description||undefined,category:category||undefined,brand:brand||undefined,...(headers.includes("shippingClass")?{shippingClassId:shippingClass?shippingClassId:null}:{}),tags:tagText?tags:undefined,...(headers.includes("internalNote")?{internalNote}:{}),supplierLinks,variants}:{clientProductId:crypto.randomUUID(),sku,name,description,category,brand,currency,shippingClassId:shippingClass?shippingClassId:null,imageFileName:image,galleryFileNames,priceTiers:tiers,tags,internalNote,supplierLinks,variants,...(weightAmount&&weightUnit?{weightAmount:Number(weightAmount),weightUnit:weightUnit as "g"|"kg"|"oz"|"lbs"}:{})});
  }
  if(data.length===1)return{rows:[],products:[],fatal:"CSV 中没有产品数据"};if(rows.length>500)return{rows,products:[],fatal:"每次最多导入 500 个产品"};return{rows,products,fatal:""};
}

export function ProductImportDialog({currencies,shippingClasses,request,onToken,onClose,onImported}:{currencies:Array<{code:string;name:string}>;shippingClasses:Array<{id:string;name:string}>;request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onClose:()=>void;onImported:(result:{created:number;updated:number})=>Promise<void>}){const inputRef=useRef<HTMLInputElement>(null),imageInputRef=useRef<HTMLInputElement>(null),[fileName,setFileName]=useState(""),[csvText,setCsvText]=useState(""),[imageFiles,setImageFiles]=useState<Map<string,File>>(new Map()),[rows,setRows]=useState<PreviewRow[]>([]),[products,setProducts]=useState<ImportProduct[]>([]),[fatal,setFatal]=useState(""),[busy,setBusy]=useState(false),[submitError,setSubmitError]=useState("");const invalid=rows.filter(row=>row.error).length;
  function preview(text:string,files:Map<string,File>){const result=buildPreview(text,currencies.map(item=>item.code),shippingClasses,new Set(files.keys()));setRows(result.rows);setProducts(result.products);setFatal(result.fatal);}
  async function choose(file:File){setFileName(file.name);setSubmitError("");try{const text=await file.text();setCsvText(text);preview(text,imageFiles);}catch{setRows([]);setProducts([]);setFatal("无法读取 CSV 文件");}}
  function chooseImages(files:FileList){const next=new Map<string,File>();for(const file of Array.from(files)){if(["image/png","image/jpeg"].includes(file.type))next.set(file.name.toLocaleLowerCase(),file);}setImageFiles(next);if(csvText)preview(csvText,next);setSubmitError(next.size?"":"未选择有效的 PNG/JPG 图片");}
  function downloadTemplate(){const csv='sku,name,description,category,brand,currency,price,price_tiers,weight_amount,weight_unit,shipping_class,tags,image,gallery_images,variants,supplier_links,internal_note\nPERFUME-001,"经典香水, 50ml","清新花香调，50ml 瓶装",香水,示例品牌,USD,29.90,,0.5,kg,Standard,新品|香水,PERFUME-001.jpg,PERFUME-001.jpg,"[{""attributes"":{""Color"":""Black""},""sku"":""PERFUME-001-BLK"",""priceTiers"":[{""minQuantity"":1,""unitAmount"":29.9}],""imageFileName"":""PERFUME-001-BLK.jpg""}]","[{""label"":""1688"",""url"":""https://example.com"",""supplyPrice"":12.5}]",采购备注\n',url=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download="product-import-template.csv";link.click();URL.revokeObjectURL(url);}
  async function submit(){setBusy(true);setSubmitError("");try{const uploaded=new Map<string,string>();for(const product of products){const names=[product.imageFileName??"",...(product.galleryFileNames??[]),...(product.variants??[]).map(item=>item.imageFileName??"")].filter(Boolean);for(const name of names){const key=name.toLocaleLowerCase();if(uploaded.has(key))continue;const file=imageFiles.get(key);if(!file)throw new Error(`找不到图片：${name}`);const form=new FormData();form.append("file",file);const result=await request("/api/v1/products/media",{method:"POST",body:form});onToken(result.token);if(!result.response.ok)throw new Error(`图片 ${file.name} 上传失败（HTTP ${result.response.status}）`);uploaded.set(key,String((await result.response.json() as {mediaId:string}).mediaId));}}const payload=products.map(({imageFileName,galleryFileNames,...product})=>({...product,imageMediaId:imageFileName?uploaded.get(imageFileName.toLocaleLowerCase()):undefined,galleryMediaIds:galleryFileNames?.map(name=>uploaded.get(name.toLocaleLowerCase())).filter((id):id is string=>Boolean(id)),variants:product.variants?.map(({imageFileName:variantImage,...variant})=>({...variant,imageMediaId:variantImage?uploaded.get(variantImage.toLocaleLowerCase()):undefined}))})),result=await request("/api/v1/products/bulk-import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({products:payload})});onToken(result.token);const body=await result.response.json().catch(()=>({})) as {error?:string;message?:string;created?:number;updated?:number};if(!result.response.ok)throw new Error(body.message??`导入失败（HTTP ${result.response.status}）`);await onImported({created:body.created??0,updated:body.updated??0});}catch(reason){setSubmitError(reason instanceof Error?reason.message:"导入失败");setBusy(false);}}
  return <div className="modal-backdrop product-dialog-backdrop" role="presentation"><section className="login-dialog product-import-dialog" role="dialog" aria-modal="true" aria-labelledby="product-import-title"><button className="login-close" onClick={onClose} disabled={busy} aria-label="关闭"><X size={17}/></button><span className="login-logo"><FileText size={20}/></span><h2 id="product-import-title">CSV 批量导入产品</h2><p>已有 SKU 可只填写 SKU 和产品名称；其他资料保持不变。新 SKU 需要填写币种和价格以完整创建。</p><div className="product-import-actions"><button className="secondary-action" onClick={downloadTemplate}><Download size={14}/>下载 CSV 模板</button><button className="primary-action" onClick={()=>inputRef.current?.click()}><UploadCloud size={14}/>{fileName||"选择 CSV 文件"}</button><input ref={inputRef} type="file" accept=".csv,text/csv" hidden onChange={event=>{const file=event.target.files?.[0];if(file)void choose(file);event.currentTarget.value="";}}/></div><div className="product-import-image-picker"><span>产品图片 · 可选 · 已选择 {imageFiles.size} 张</span><button className="secondary-action" onClick={()=>imageInputRef.current?.click()}><UploadCloud size={14}/>选择多张图片</button><input ref={imageInputRef} type="file" accept="image/png,image/jpeg" multiple hidden onChange={event=>{if(event.target.files)chooseImages(event.target.files);event.currentTarget.value="";}}/></div>{fatal&&<span className="login-error">{fatal}</span>}{rows.length>0&&<><div className={`product-import-summary ${invalid?"invalid":""}`}><b>{rows.length} 行产品</b><span>{invalid?`${invalid} 行需要修正`:`校验通过，可导入或更新 ${products.length} 个产品`}</span></div><div className="product-import-preview"><table><thead><tr><th>行</th><th>SKU</th><th>产品名称</th><th>描述</th><th>币种</th><th>价格</th><th>标签</th><th>图片</th><th>校验结果</th></tr></thead><tbody>{rows.slice(0,100).map(row=><tr key={row.line} className={row.error?"invalid":""}><td>{row.line}</td><td>{row.sku}</td><td>{row.name}</td><td>{row.description||"—"}</td><td>{row.currency||"—"}</td><td>{row.tiers||row.price||"—"}</td><td>{row.tags||"—"}</td><td>{row.image||"—"}</td><td>{row.error||"通过"}</td></tr>)}</tbody></table>{rows.length>100&&<p>仅预览前 100 行，其余行也已完成校验。</p>}</div></>}{submitError&&<span className="login-error">{submitError}</span>}<button className="login-submit" disabled={busy||!rows.length||Boolean(fatal)||invalid>0} onClick={()=>void submit()}>{busy?"正在上传图片并导入…":`导入或更新 ${products.length} 个产品`}</button></section></div>;
}
