"use client";

import { Download, FileText, UploadCloud, X } from "lucide-react";
import { useRef, useState } from "react";

type RequestResult={response:Response;token:string};
type ImportProduct={clientProductId:string;sku:string;name:string;description:string;currency:string;imageFileName:string;imageMediaId?:string;priceTiers:Array<{minQuantity:number;unitAmount:number}>;tags:Array<{name:string;color:string}>};
type PreviewRow={line:number;sku:string;name:string;description:string;currency:string;price:string;tiers:string;tags:string;image:string;error:string};
const HEADER_ALIASES:Record<string,string>={sku:"sku","产品编号":"sku","产品sku":"sku",name:"name","名称":"name","产品名称":"name",description:"description","产品描述":"description","描述":"description",currency:"currency","币种":"currency",price:"price","unit_price":"price","单价":"price","默认单价":"price",price_tiers:"tiers","价格阶梯":"tiers","阶梯价格":"tiers",tags:"tags","标签":"tags",image:"image",image_file:"image",image_filename:"image","图片":"image","图片文件名":"image"};
const TAG_COLORS=["#E8EEF7","#E8F7EE","#FFF1D6","#F7E8EF","#EEE8F7"];

export function parseCsv(text:string):string[][]{const rows:string[][]=[];let row:string[]=[],field="",quoted=false;const source=text.replace(/^\uFEFF/,"");for(let index=0;index<source.length;index++){const char=source[index];if(quoted){if(char==='"'&&source[index+1]==='"'){field+='"';index++;}else if(char==='"')quoted=false;else field+=char;}else if(char==='"'&&!field)quoted=true;else if(char===","){row.push(field);field="";}else if(char==="\n"){row.push(field);if(row.some(value=>value.trim()))rows.push(row);row=[];field="";}else if(char!=="\r")field+=char;}row.push(field);if(row.some(value=>value.trim()))rows.push(row);return rows;}

function buildPreview(text:string,currencies:string[],imageNames:Set<string>):{rows:PreviewRow[];products:ImportProduct[];fatal:string}{
  const data=parseCsv(text);if(!data.length)return{rows:[],products:[],fatal:"CSV 文件为空"};
  const headers=data[0].map(value=>HEADER_ALIASES[value.trim().toLocaleLowerCase()]??"");
  for(const required of ["sku","name","currency"])if(!headers.includes(required))return{rows:[],products:[],fatal:`缺少必填列：${required}`};
  if(!headers.includes("price")&&!headers.includes("tiers"))return{rows:[],products:[],fatal:"需要 price（单价）或 price_tiers（阶梯价格）列"};
  const index=(name:string)=>headers.indexOf(name),seen=new Set<string>(),products:ImportProduct[]=[],rows:PreviewRow[]=[],moneyPattern=/^\d+(?:\.\d{1,2})?$/;
  for(const [offset,values] of data.slice(1).entries()){
    const value=(name:string)=>String(values[index(name)]??"").trim(),sku=value("sku"),name=value("name"),description=value("description"),currency=value("currency").toUpperCase(),price=value("price"),tierText=value("tiers"),tagText=value("tags"),image=value("image"),tierParts=tierText?tierText.split(/[|；;]/).filter(Boolean):[];
    const tierSyntaxValid=tierParts.every(item=>/^\d+[:：]\d+(?:\.\d{1,2})?$/.test(item.trim())),tiers=tierText?tierParts.map(item=>{const parts=item.trim().split(/[:：]/);return{minQuantity:Number(parts[0]),unitAmount:Number(parts[1])};}):[{minQuantity:1,unitAmount:Number(price)}];let error="";
    if(!sku||sku.length>80)error="SKU 必填且不能超过 80 个字符";else if(seen.has(sku.toLocaleLowerCase()))error="CSV 中 SKU 重复";else if(!name||name.length>120)error="产品名称必填且不能超过 120 个字符";else if(description.length>2000)error="产品描述不能超过 2000 个字符";else if(!currencies.includes(currency))error=`币种 ${currency||"（空）"} 未启用`;else if((!tierText&&!moneyPattern.test(price))||(tierText&&!tierSyntaxValid)||!tiers.length||tiers.some((tier,tierIndex)=>tier.minQuantity<1||(tierIndex===0?tier.minQuantity!==1:tier.minQuantity<=tiers[tierIndex-1].minQuantity)))error="价格格式错误；阶梯价格示例：1:99.00|10:89.00";else if(image&&!imageNames.has(image.toLocaleLowerCase()))error=`未选择图片文件：${image}`;
    const tags=tagText.split(/[|；;]/).map(item=>item.trim()).filter(Boolean).map((tag,tagIndex)=>({name:tag,color:TAG_COLORS[tagIndex%TAG_COLORS.length]}));if(tags.some(tag=>tag.name.length>40)||tags.length>30)error=error||"标签不能超过 30 个，每个最多 40 个字符";
    seen.add(sku.toLocaleLowerCase());const preview={line:offset+2,sku,name,description,currency,price,tiers:tierText,tags:tagText,image,error};rows.push(preview);if(!error)products.push({clientProductId:crypto.randomUUID(),sku,name,description,currency,imageFileName:image,priceTiers:tiers,tags});
  }
  if(data.length===1)return{rows:[],products:[],fatal:"CSV 中没有产品数据"};if(rows.length>500)return{rows,products:[],fatal:"每次最多导入 500 个产品"};return{rows,products,fatal:""};
}

export function ProductImportDialog({currencies,request,onToken,onClose,onImported}:{currencies:Array<{code:string;name:string}>;request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onClose:()=>void;onImported:(count:number)=>Promise<void>}){const inputRef=useRef<HTMLInputElement>(null),imageInputRef=useRef<HTMLInputElement>(null),[fileName,setFileName]=useState(""),[csvText,setCsvText]=useState(""),[imageFiles,setImageFiles]=useState<Map<string,File>>(new Map()),[rows,setRows]=useState<PreviewRow[]>([]),[products,setProducts]=useState<ImportProduct[]>([]),[fatal,setFatal]=useState(""),[busy,setBusy]=useState(false),[submitError,setSubmitError]=useState("");const invalid=rows.filter(row=>row.error).length;
  function preview(text:string,files:Map<string,File>){const result=buildPreview(text,currencies.map(item=>item.code),new Set(files.keys()));setRows(result.rows);setProducts(result.products);setFatal(result.fatal);}
  async function choose(file:File){setFileName(file.name);setSubmitError("");try{const text=await file.text();setCsvText(text);preview(text,imageFiles);}catch{setRows([]);setProducts([]);setFatal("无法读取 CSV 文件");}}
  function chooseImages(files:FileList){const next=new Map<string,File>();for(const file of Array.from(files)){if(["image/png","image/jpeg"].includes(file.type))next.set(file.name.toLocaleLowerCase(),file);}setImageFiles(next);if(csvText)preview(csvText,next);setSubmitError(next.size?"":"未选择有效的 PNG/JPG 图片");}
  function downloadTemplate(){const csv='sku,name,description,currency,price,price_tiers,tags,image\nPERFUME-001,"经典香水, 50ml","清新花香调，50ml 瓶装",USD,29.90,,新品|香水,PERFUME-001.jpg\nPERFUME-002,礼盒装,节日礼盒套装,USD,,1:49.90|10:44.90,礼盒|热销,PERFUME-002.png\n',url=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download="product-import-template.csv";link.click();URL.revokeObjectURL(url);}
  async function submit(){setBusy(true);setSubmitError("");try{const uploaded=new Map<string,string>();for(const product of products){const key=product.imageFileName.toLocaleLowerCase();if(!key||uploaded.has(key))continue;const file=imageFiles.get(key);if(!file)throw new Error(`找不到图片：${product.imageFileName}`);const form=new FormData();form.append("file",file);const result=await request("/api/v1/products/media",{method:"POST",body:form});onToken(result.token);if(!result.response.ok)throw new Error(`图片 ${file.name} 上传失败（HTTP ${result.response.status}）`);uploaded.set(key,String((await result.response.json() as {mediaId:string}).mediaId));}const payload=products.map(({imageFileName,...product})=>({...product,imageMediaId:imageFileName?uploaded.get(imageFileName.toLocaleLowerCase()):undefined})),result=await request("/api/v1/products/bulk-import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({products:payload})});onToken(result.token);const body=await result.response.json().catch(()=>({})) as {error?:string;message?:string;skus?:string[];created?:number};if(!result.response.ok)throw new Error(body.error==="sku_exists"?`以下 SKU 已存在：${body.skus?.join("、")||"请刷新产品库后检查"}`:body.message??`导入失败（HTTP ${result.response.status}）`);await onImported(body.created??products.length);}catch(reason){setSubmitError(reason instanceof Error?reason.message:"导入失败");setBusy(false);}}
  return <div className="modal-backdrop product-dialog-backdrop" role="presentation"><section className="login-dialog product-import-dialog" role="dialog" aria-modal="true" aria-labelledby="product-import-title"><button className="login-close" onClick={onClose} disabled={busy} aria-label="关闭"><X size={17}/></button><span className="login-logo"><FileText size={20}/></span><h2 id="product-import-title">CSV 批量导入产品</h2><p>CSV 的 image 列填写图片文件名，再一次选择对应图片。阶梯价格和标签均使用 | 分隔。</p><div className="product-import-actions"><button className="secondary-action" onClick={downloadTemplate}><Download size={14}/>下载 CSV 模板</button><button className="primary-action" onClick={()=>inputRef.current?.click()}><UploadCloud size={14}/>{fileName||"选择 CSV 文件"}</button><input ref={inputRef} type="file" accept=".csv,text/csv" hidden onChange={event=>{const file=event.target.files?.[0];if(file)void choose(file);event.currentTarget.value="";}}/></div><div className="product-import-image-picker"><span>产品图片 · 可选 · 已选择 {imageFiles.size} 张</span><button className="secondary-action" onClick={()=>imageInputRef.current?.click()}><UploadCloud size={14}/>选择多张图片</button><input ref={imageInputRef} type="file" accept="image/png,image/jpeg" multiple hidden onChange={event=>{if(event.target.files)chooseImages(event.target.files);event.currentTarget.value="";}}/></div>{fatal&&<span className="login-error">{fatal}</span>}{rows.length>0&&<><div className={`product-import-summary ${invalid?"invalid":""}`}><b>{rows.length} 行产品</b><span>{invalid?`${invalid} 行需要修正`:`校验通过，可导入 ${products.length} 个产品`}</span></div><div className="product-import-preview"><table><thead><tr><th>行</th><th>SKU</th><th>产品名称</th><th>描述</th><th>币种</th><th>价格</th><th>标签</th><th>图片</th><th>校验结果</th></tr></thead><tbody>{rows.slice(0,100).map(row=><tr key={row.line} className={row.error?"invalid":""}><td>{row.line}</td><td>{row.sku}</td><td>{row.name}</td><td>{row.description||"—"}</td><td>{row.currency}</td><td>{row.tiers||row.price}</td><td>{row.tags||"—"}</td><td>{row.image||"—"}</td><td>{row.error||"通过"}</td></tr>)}</tbody></table>{rows.length>100&&<p>仅预览前 100 行，其余行也已完成校验。</p>}</div></>}{submitError&&<span className="login-error">{submitError}</span>}<button className="login-submit" disabled={busy||!rows.length||Boolean(fatal)||invalid>0} onClick={()=>void submit()}>{busy?"正在上传图片并导入…":`导入 ${products.length} 个产品`}</button></section></div>;
}
