"use client";

import { FileText, Paperclip, Search, UploadCloud, X } from "lucide-react";
import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";
import { clipboardFiles } from "./clipboard-files";

type RequestResult={response:Response;token:string};
export type ProductImageAsset={id:string;fileName:string;mimeType:string;size:number;sha256:string;createdAt:string;usageCount:number};

export function ProductImageMediaDialog({request,onToken,onClose,onSelect,libraryPath,uploadPath,description="仅显示可用的 PNG 和 JPG 图片。"}:{request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onClose:()=>void;onSelect:(asset:ProductImageAsset)=>void;libraryPath:string;uploadPath:string;description?:string}){
  const [assets,setAssets]=useState<ProductImageAsset[]>([]),[selectedId,setSelectedId]=useState(""),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[dragging,setDragging]=useState(false),[error,setError]=useState("");
  const inputRef=useRef<HTMLInputElement>(null);
  const load=useCallback(async()=>{const result=await request(libraryPath);onToken(result.token);if(!result.response.ok){setError(`媒体库加载失败（HTTP ${result.response.status}）`);return;}const body=await result.response.json() as {data:Array<Record<string,unknown>>};setAssets(body.data.map(mapAsset).filter(item=>["image/png","image/jpeg"].includes(item.mimeType)));},[libraryPath,onToken,request]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!busy)onClose();};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[busy,onClose]);
  useEffect(()=>{const paste=(event:ClipboardEvent)=>{if(busy)return;void (async()=>{const images=await clipboardFiles(event,{imagesOnly:true});if(!images.length)return;event.preventDefault();await upload(images);})();};window.addEventListener("paste",paste);return()=>window.removeEventListener("paste",paste);});
  const visible=assets.filter(item=>!query||item.fileName.toLowerCase().includes(query.toLowerCase())),selected=assets.find(item=>item.id===selectedId)??null;
  async function upload(files:FileList|File[]){const list=Array.from(files);if(!list.length)return;setBusy(true);setError("");try{let lastId="";for(const file of list){if(!["image/png","image/jpeg"].includes(file.type))throw new Error(`${file.name} 不是 PNG 或 JPG 图片`);if(file.size>64*1024*1024)throw new Error(`${file.name} 超过 64 MB`);const form=new FormData();form.append("file",file);const result=await request(uploadPath,{method:"POST",body:form});onToken(result.token);if(!result.response.ok)throw new Error(`${file.name} 上传失败（HTTP ${result.response.status}）`);lastId=String((await result.response.json() as {mediaId:string}).mediaId);}await load();setSelectedId(lastId);}catch(reason){setError(reason instanceof Error?reason.message:"上传失败");}finally{setBusy(false);setDragging(false);}}
  return <div className="modal-backdrop media-backdrop product-image-media-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}><section className="media-dialog product-image-media-dialog" role="dialog" aria-modal="true" aria-labelledby="product-image-media-title">
    <header><div><span className="login-logo"><Paperclip size={21}/></span><span><h2 id="product-image-media-title">从媒体与附件选择</h2><p>{description}</p></span></div><button className="login-close" onClick={onClose} disabled={busy} aria-label="关闭"><X size={17}/></button></header>
    <div className={`media-dropzone ${dragging?"dragging":""}`} onDragEnter={event=>{event.preventDefault();setDragging(true);}} onDragOver={event=>event.preventDefault()} onDragLeave={event=>{if(event.currentTarget===event.target)setDragging(false);}} onDrop={event=>{event.preventDefault();void upload(event.dataTransfer.files);}} onClick={()=>inputRef.current?.click()} role="button" tabIndex={0} onKeyDown={event=>{if(event.key==="Enter"||event.key===" ")inputRef.current?.click();}}><UploadCloud size={30}/><b>{busy?"正在上传…":"拖拽、粘贴图片，或点击选择"}</b><span>PNG 或 JPG；单文件最大 64 MB</span><input ref={inputRef} type="file" multiple accept="image/png,image/jpeg" onChange={event=>{if(event.target.files)void upload(event.target.files);event.currentTarget.value="";}}/></div>
    <div className="media-library-head"><div><b>图片</b><span>{assets.length} 个文件</span></div><label><Search size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索文件名"/></label></div>
    <div className="media-grid product-image-media-grid">{visible.length?visible.map(asset=><button key={asset.id} className={`media-item ${selectedId===asset.id?"selected":""}`} onClick={()=>setSelectedId(asset.id)}><MediaPreview asset={asset} request={request} onToken={onToken}/><span><b title={asset.fileName}>{asset.fileName}</b><small>{formatBytes(asset.size)} · {asset.usageCount?`已使用 ${asset.usageCount} 次`:"未使用"}</small></span></button>):<div className="media-empty"><FileText size={28}/><b>媒体与附件中暂无匹配图片</b><span>可从上方上传 PNG 或 JPG</span></div>}</div>
    {error&&<span className="login-error media-error">{error}</span>}<footer className="product-image-media-footer"><span>{selected?.fileName||"尚未选择图片"}</span><button className="secondary-action" onClick={onClose} disabled={busy}>取消</button><button className="primary-action" disabled={!selected||busy} onClick={()=>selected&&onSelect(selected)}>使用所选图片</button></footer>
  </section></div>;
}

function MediaPreview({asset,request,onToken}:{asset:ProductImageAsset;request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void}){const [url,setUrl]=useState("");useEffect(()=>{const controller=new AbortController();let objectUrl="";void (async()=>{try{const result=await request(`/api/v1/media/${asset.id}`,{signal:controller.signal});onToken(result.token);if(!result.response.ok)return;objectUrl=URL.createObjectURL(await result.response.blob());if(!controller.signal.aborted)setUrl(objectUrl);}catch{}})();return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[asset.id,onToken,request]);return <span className="media-image-preview">{url?<Image src={url} alt={asset.fileName} width={240} height={180} unoptimized/>:<FileText size={24}/>}</span>;}
function mapAsset(item:Record<string,unknown>):ProductImageAsset{return{id:String(item.id),fileName:String(item.file_name??item.fileName??"未命名文件"),mimeType:String(item.mime_type??item.mimeType??"application/octet-stream"),size:Number(item.byte_size??item.size??0),sha256:String(item.sha256??""),createdAt:String(item.created_at??item.createdAt??""),usageCount:Number(item.usage_count??item.usageCount??0)};}
function formatBytes(size:number){if(size<1024)return`${size} B`;if(size<1048576)return`${(size/1024).toFixed(1)} KB`;return`${(size/1048576).toFixed(1)} MB`;}
