"use client";

import { Check, Plus, RefreshCw, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { WEIGHT_UNITS, type WeightUnit } from "./weight";

type RequestResult={response:Response;token:string};
type ShippingClass={id:string;name:string;enabled:boolean};
type Rule={shippingClassId:string|null;shippingClassName?:string|null;mode:"quantity"|"weight";firstItemPrice?:number;additionalItemPrice?:number;firstWeight?:number;additionalWeight?:number;weightUnit?:WeightUnit;firstWeightPrice?:number;additionalWeightPrice?:number};
type Template={id:string;name:string;currency:string;enabled:boolean;isDefault:boolean;version:number;rules:Rule[]};
type RuleDraft={id:string;shippingClassId:string;mode:"quantity"|"weight";firstItemPrice:string;additionalItemPrice:string;firstWeight:string;additionalWeight:string;weightUnit:WeightUnit;firstWeightPrice:string;additionalWeightPrice:string};
type TemplateDraft={id:string;name:string;currency:string;enabled:boolean;isDefault:boolean;rules:RuleDraft[]};

const newRule=(shippingClassId="",source?:Rule):RuleDraft=>({id:crypto.randomUUID(),shippingClassId,mode:source?.mode??"quantity",firstItemPrice:String(source?.firstItemPrice??0),additionalItemPrice:String(source?.additionalItemPrice??0),firstWeight:String(source?.firstWeight??1),additionalWeight:String(source?.additionalWeight??1),weightUnit:source?.weightUnit??"kg",firstWeightPrice:String(source?.firstWeightPrice??0),additionalWeightPrice:String(source?.additionalWeightPrice??0)});
const editTemplate=(item:Template):TemplateDraft=>({id:item.id,name:item.name,currency:item.currency,enabled:item.enabled,isDefault:item.isDefault,rules:item.rules.map(rule=>newRule(rule.shippingClassId??"",rule))});

export function ShippingSettings({request,onToken,onToast}:{request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onToast:(text:string)=>void}){
  const [classes,setClasses]=useState<ShippingClass[]>([]),[templates,setTemplates]=useState<Template[]>([]),[currencies,setCurrencies]=useState<Array<{code:string;name:string}>>([]),[draft,setDraft]=useState<TemplateDraft|null>(null),[newClassName,setNewClassName]=useState(""),[classRuleId,setClassRuleId]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const [a,b,c]=await Promise.all([request("/api/v1/admin/shipping-classes"),request("/api/v1/admin/shipping-templates"),request("/api/v1/currencies")]);onToken(a.token);const classBody=await a.response.json() as {data?:ShippingClass[];error?:string},templateBody=await b.response.json() as {data?:Template[];error?:string},currencyBody=await c.response.json() as {currencies?:Array<{code:string;name:string}>};if(!a.response.ok||!b.response.ok)throw new Error(classBody.error??templateBody.error??"加载失败");setClasses(classBody.data??[]);setTemplates(templateBody.data??[]);setCurrencies(currencyBody.currencies??[]);setDraft(current=>{const selected=(templateBody.data??[]).find(item=>item.id===current?.id)??(templateBody.data??[])[0];return selected?editTemplate(selected):null;});setError("");}catch(reason){setError(reason instanceof Error?reason.message:"加载失败");}finally{setLoading(false);}},[request,onToken]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  function changeRule(id:string,change:Partial<RuleDraft>){setDraft(value=>value?{...value,rules:value.rules.map(rule=>rule.id===id?{...rule,...change}:rule)}:value);}
  async function createClass(){if(!newClassName.trim())return;setBusy(true);const result=await request("/api/v1/admin/shipping-classes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:newClassName.trim(),enabled:true})});onToken(result.token);setBusy(false);if(!result.response.ok){setError("新增 shipping class 失败");return;}setNewClassName("");await load();}
  async function toggleClass(item:ShippingClass){setBusy(true);const result=await request(`/api/v1/admin/shipping-classes/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:!item.enabled})});onToken(result.token);setBusy(false);if(result.response.ok)await load();else setError("更新 shipping class 失败");}
  function createTemplate(){setDraft({id:"",name:"新运费模板",currency:currencies[0]?.code??"USD",enabled:true,isDefault:templates.length===0,rules:[newRule()]});}
  async function save(){if(!draft)return;setBusy(true);setError("");const payload={name:draft.name.trim(),currency:draft.currency,enabled:draft.enabled,isDefault:draft.isDefault,rules:draft.rules.map(rule=>rule.mode==="quantity"?{shippingClassId:rule.shippingClassId||null,mode:rule.mode,firstItemPrice:Number(rule.firstItemPrice),additionalItemPrice:Number(rule.additionalItemPrice)}:{shippingClassId:rule.shippingClassId||null,mode:rule.mode,firstWeight:Number(rule.firstWeight),additionalWeight:Number(rule.additionalWeight),weightUnit:rule.weightUnit,firstWeightPrice:Number(rule.firstWeightPrice),additionalWeightPrice:Number(rule.additionalWeightPrice)})},result=await request(draft.id?`/api/v1/admin/shipping-templates/${draft.id}`:"/api/v1/admin/shipping-templates",{method:draft.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});onToken(result.token);setBusy(false);if(!result.response.ok){const body=await result.response.json().catch(()=>({})) as {error?:string;message?:string};setError(body.message??body.error??"保存失败");return;}const saved=await result.response.json() as Template;await load();setDraft(editTemplate(saved));onToast("运费模板已保存");}
  async function remove(){if(!draft?.id||draft.isDefault)return;setBusy(true);const result=await request(`/api/v1/admin/shipping-templates/${draft.id}`,{method:"DELETE"});onToken(result.token);setBusy(false);if(result.response.ok){setDraft(null);await load();}else setError("无法删除默认模板");}
  if(loading)return <p>正在读取运费设置…</p>;
  return <div className="shipping-settings-layout">
    <aside className="shipping-class-panel">
      <h3>Shipping classes</h3><p>停用不会改变产品和历史订单快照。</p>
      <div className="shipping-class-create"><input value={newClassName} placeholder="例如：Heavy" onChange={event=>setNewClassName(event.target.value)}/><button disabled={busy||!newClassName.trim()} onClick={()=>void createClass()}><Plus size={13}/></button></div>
      {classes.map(item=><div className="shipping-class-row" key={item.id}><span><b>{item.name}</b><small>{item.enabled?"启用":"停用"}</small></span><button disabled={busy} onClick={()=>void toggleClass(item)}>{item.enabled?"停用":"启用"}</button></div>)}
    </aside>
    <section className="settings-provider-section shipping-template-panel">
      <div className="settings-section-head"><div><h2>运费模板</h2><p>各 shipping class 分组计算后累加，未覆盖时使用默认规则。</p></div><div><button className="secondary-action" onClick={()=>void load()}><RefreshCw size={14}/>刷新</button><button className="primary-action" onClick={createTemplate}><Plus size={14}/>新增模板</button></div></div>
      <nav className="order-settings-tabs">{templates.map(item=><button key={item.id} className={draft?.id===item.id?"active":""} onClick={()=>setDraft(editTemplate(item))}>{item.name}{item.isDefault?" · 默认":""}{!item.enabled?" · 停用":""}</button>)}</nav>
      {draft?<div className="shipping-template-editor">
        <div className="provider-form-grid"><label>模板名称<input value={draft.name} onChange={event=>setDraft(value=>value&&({...value,name:event.target.value}))}/></label><label>模板币种<select value={draft.currency} onChange={event=>setDraft(value=>value&&({...value,currency:event.target.value}))}>{currencies.map(item=><option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select></label></div>
        <div className="shipping-template-switches"><label className="provider-toggle"><input type="checkbox" checked={draft.enabled} onChange={event=>setDraft(value=>value&&({...value,enabled:event.target.checked,isDefault:event.target.checked?value.isDefault:false}))}/><span>启用</span></label><label className="provider-toggle"><input type="checkbox" checked={draft.isDefault} disabled={!draft.enabled} onChange={event=>setDraft(value=>value&&({...value,isDefault:event.target.checked}))}/><span>默认模板</span></label></div>
        <div className="shipping-rule-list">{draft.rules.map((rule,index)=><article key={rule.id}><header><b>{index===0?"默认规则":classes.find(item=>item.id===rule.shippingClassId)?.name}</b><select value={rule.mode} onChange={event=>changeRule(rule.id,{mode:event.target.value as RuleDraft["mode"]})}><option value="quantity">按数量</option><option value="weight">按重量</option></select>{index>0&&<button onClick={()=>setDraft(value=>value?{...value,rules:value.rules.filter(item=>item.id!==rule.id)}:value)}><Trash2 size={13}/></button>}</header>{rule.mode==="quantity"?<div className="provider-form-grid"><label>首件价格<input value={rule.firstItemPrice} onChange={event=>changeRule(rule.id,{firstItemPrice:event.target.value})}/></label><label>续件价格<input value={rule.additionalItemPrice} onChange={event=>changeRule(rule.id,{additionalItemPrice:event.target.value})}/></label></div>:<div className="provider-form-grid"><label>首重<input value={rule.firstWeight} onChange={event=>changeRule(rule.id,{firstWeight:event.target.value})}/></label><label>续重<input value={rule.additionalWeight} onChange={event=>changeRule(rule.id,{additionalWeight:event.target.value})}/></label><label>单位<select value={rule.weightUnit} onChange={event=>changeRule(rule.id,{weightUnit:event.target.value as WeightUnit})}>{WEIGHT_UNITS.map(unit=><option key={unit}>{unit}</option>)}</select></label><label>首重价格<input value={rule.firstWeightPrice} onChange={event=>changeRule(rule.id,{firstWeightPrice:event.target.value})}/></label><label>续重价格<input value={rule.additionalWeightPrice} onChange={event=>changeRule(rule.id,{additionalWeightPrice:event.target.value})}/></label></div>}</article>)}</div>
        <div className="shipping-rule-add"><select value={classRuleId} onChange={event=>setClassRuleId(event.target.value)}><option value="">选择 class…</option>{classes.filter(item=>item.enabled&&!draft.rules.some(rule=>rule.shippingClassId===item.id)).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={!classRuleId} onClick={()=>{setDraft(value=>value?{...value,rules:[...value.rules,newRule(classRuleId)]}:value);setClassRuleId("");}}><Plus size={13}/>添加覆盖</button></div>
        {error&&<span className="login-error">{error}</span>}<footer><button className="danger-text" disabled={!draft.id||draft.isDefault||busy} onClick={()=>void remove()}><Trash2 size={14}/>删除</button><button className="primary-action" disabled={busy||!draft.name.trim()} onClick={()=>void save()}><Check size={14}/>{busy?"保存中…":"保存模板"}</button></footer>
      </div>:<p className="order-empty-fees">暂无模板，请先新增。</p>}
    </section>
  </div>;
}
