"use client";
import { Check, Plus, Sparkles, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";

type Source={id?:string;name:string;baseUrl:string};
type Product={clientProductId:string;sku:string;name:string;description:string;category:string;brand:string;currency:string;priceTiers:Array<{minQuantity:number;unitAmount:number}>;galleryExternalUrls:string[];tags:Array<{name:string;color:string}>};
type RequestResult={response:Response;token:string};

export function SmartProductImportDialog({currencies,request,onToken,onClose,onImported}:{currencies:Array<{code:string;name:string}>;request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onClose:()=>void;onImported:(result:{created:number;updated:number})=>void}){
 const [sources,setSources]=useState<Source[]>([]),[sourceId,setSourceId]=useState(""),[text,setText]=useState(""),[currency,setCurrency]=useState(currencies[0]?.code??"USD"),[price,setPrice]=useState("0"),[products,setProducts]=useState<Product[]>([]),[missing,setMissing]=useState<string[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{void request("/api/v1/admin/product-import-sources").then(async result=>{if(result.token)onToken(result.token);if(result.response.ok){const body=await result.response.json() as {sources:Source[]};setSources(body.sources);setSourceId(body.sources[0]?.baseUrl??"");}})},[request,onToken]);
 function parseSkus(){const skus=[...text.matchAll(/(?:SKU\s*[:：]?\s*)?([0-9]{3,})/gi)].map(match=>match[1]);return [...new Set(skus)];}
 async function search(){setBusy(true);setError("");try{const skus=parseSkus();if(!sourceId||!skus.length)throw new Error("请选择来源并输入 SKU 列表");const result=await request("/api/v1/products/smart-import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({baseUrl:sourceId,skus,currency,price:Number(price)||0})});if(result.token)onToken(result.token);const body=await result.response.json() as {products?:Product[];missing?:string[];errors?:Array<{sku:string;error:string}>;message?:string};if(!result.response.ok)throw new Error(body.message??`查询失败（HTTP ${result.response.status}）`);setProducts(body.products??[]);setMissing([...(body.missing??[]),...(body.errors??[]).map(item=>`${item.sku}（${item.error}）`)]);}catch(reason){setError(reason instanceof Error?reason.message:"查询失败");}finally{setBusy(false);}}
 async function importProducts(){setBusy(true);setError("");try{const result=await request("/api/v1/products/bulk-import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({products})});if(result.token)onToken(result.token);const body=await result.response.json() as {created?:number;updated?:number;message?:string};if(!result.response.ok)throw new Error(body.message??`导入失败（HTTP ${result.response.status}）`);onImported({created:body.created??0,updated:body.updated??0});}catch(reason){setError(reason instanceof Error?reason.message:"导入失败");}finally{setBusy(false);}}
 return <div className="modal-backdrop product-dialog-backdrop"><section className="login-dialog product-import-dialog smart-product-import-dialog"><button className="login-close" onClick={onClose} disabled={busy}><X size={17}/></button><span className="login-logo"><Sparkles size={20}/></span><h2>智能导入产品</h2><p>粘贴询盘列表，按 SKU 从外部产品库获取商品信息。</p><label>产品来源<select value={sourceId} onChange={event=>setSourceId(event.target.value)}>{sources.map(source=><option key={source.baseUrl} value={source.baseUrl}>{source.name} · {source.baseUrl}</option>)}</select></label><label>SKU 列表<textarea value={text} onChange={event=>setText(event.target.value)} rows={8} placeholder={'SKU: 167297 × 1\n/products/bvlgari-167297/\n\nSKU: 170050 × 1'}/></label><div className="product-form-grid"><label>导入币种<select value={currency} onChange={event=>setCurrency(event.target.value)}>{currencies.map(item=><option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select></label><label>默认单价<input type="number" min="0" step="0.01" value={price} onChange={event=>setPrice(event.target.value)}/></label></div>{products.length>0&&<><div className="product-import-summary"><b>已获取 {products.length} 个产品</b><span>{missing.length?`未找到或失败 ${missing.length} 个`:"全部 SKU 查询成功"}</span></div><div className="product-import-preview"><table><thead><tr><th>SKU</th><th>名称</th><th>品牌</th><th>图片</th></tr></thead><tbody>{products.map(product=><tr key={product.sku}><td>{product.sku}</td><td>{product.name}</td><td>{product.brand||"—"}</td><td>{product.galleryExternalUrls.length} 张</td></tr>)}</tbody></table></div></>}{missing.length>0&&<p className="smart-import-missing">未处理：{missing.join("、")}</p>}{error&&<span className="login-error">{error}</span>}<footer className="smart-import-footer"><button className="secondary-action" onClick={onClose} disabled={busy}>取消</button><button className="secondary-action" onClick={()=>void search()} disabled={busy}><Sparkles size={14}/>{busy?"处理中…":"查询产品"}</button><button className="primary-action" onClick={()=>void importProducts()} disabled={busy||!products.length}><Check size={14}/>导入已获取产品</button></footer></section></div>;
}