"use client";

import {useCallback,useEffect,useState,type ReactNode} from "react";
import {CalendarDays,ChevronLeft,ChevronRight,Clock3,Eye,Film,GanttChart,Image as ImageIcon,Languages,List,Pause,Play,Plus,RefreshCw,Search,Send,Trash2,UploadCloud,X} from "lucide-react";
import {MediaImagePreview,ProductImageMediaDialog,type ProductImageAsset} from "./product-image-media-dialog";
import {LanguagePicker,languageName} from "./language-picker";

type RequestResult={response:Response;token:string};
type Account={id:string;name:string;status:string;transport:"web"|"cloud"};
type Campaign={id:string;account_id:string;account_name:string;name:string;timezone:string;start_date:string;end_date:string;active_weekdays:number[];daily_start:string;daily_end:string;interval_minutes:number;status:string;recipient_count:number;post_count:number;published_count:number;account_status:string;agent_status:string;capabilities:string[]};
type Post={id:string;campaign_id:string;campaign_name:string;account_id:string;account_name:string;content_type:"text"|"image"|"video";text_content:string|null;translation_source_text:string|null;translation_target_language:string|null;file_name:string|null;status:string;scheduled_at:string|null;published_at:string|null;expires_at:string|null;last_error:string|null;position:number;recipient_count:number;timezone:string;start_date:string;end_date:string};
type Contact={id:string;name:string;phone:string};
type Tag={id:string;name:string;color:string};
type DraftItem={id:string;type:"text"|"image"|"video";text:string;sourceText:string|null;targetLanguage:string;media:ProductImageAsset|null;backgroundColor:string;font:number};
type View="list"|"gantt"|"calendar";
type WizardDates={startDate:string;endDate:string};
const STATUS:Record<string,string>={queued:"队列中",scheduled:"已排期",dispatching:"发布中",published:"已发布",failed:"失败",uncertain:"待确认",expired:"已过期",cancelled:"已取消"};
const CAMPAIGN_STATUS:Record<string,string>={draft:"草稿",active:"运行中",paused:"已暂停",completed:"已完成",cancelled:"已取消"};
const DAY=86_400_000;

export function StatusCenter({accounts,role,request,onToken,onToast}:{accounts:Account[];role:string;request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onToast:(text:string)=>void}){
  const [campaigns,setCampaigns]=useState<Campaign[]>([]),[posts,setPosts]=useState<Post[]>([]),[view,setView]=useState<View>("list"),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[accountId,setAccountId]=useState(""),[status,setStatus]=useState(""),[wizardDates,setWizardDates]=useState<WizardDates|null>(null),[cursor,setCursor]=useState(()=>new Date()),[calendarMode,setCalendarMode]=useState<"month"|"week">("month"),[displayTimezone,setDisplayTimezone]=useState(()=>Intl.DateTimeFormat().resolvedOptions().timeZone);
  const canManage=["admin","supervisor"].includes(role);
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const campaignParams=new URLSearchParams(),postParams=new URLSearchParams();if(accountId){campaignParams.set("accountId",accountId);postParams.set("accountId",accountId);}if(status)postParams.set("status",status);if(query.trim()){campaignParams.set("q",query.trim());postParams.set("q",query.trim());}const init=signal?{signal}:undefined,[campaignResult,postResult]=await Promise.all([request(`/api/v1/status-campaigns?${campaignParams}`,init),request(`/api/v1/status-posts?${postParams}`,init)]);if(!campaignResult.response.ok||!postResult.response.ok)throw new Error("动态排期加载失败");setCampaigns((await campaignResult.response.json() as {data:Campaign[]}).data);setPosts((await postResult.response.json() as {data:Post[]}).data);}catch(error){if(signal?.aborted)return;onToast(error instanceof Error?error.message:"动态排期加载失败");}finally{if(!signal?.aborted)setLoading(false);}},[request,accountId,status,query,onToast]);
  useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),query?250:0);return()=>{clearTimeout(timer);controller.abort();};},[load,query]);
  const mutate=async(path:string,method="POST")=>{const result=await request(path,{method});const body=await result.response.json().catch(()=>({})) as {error?:string};if(!result.response.ok){onToast(errorText(body.error));return;}onToast("操作已完成");await load();};
  const webAccounts=accounts.filter(account=>account.transport==="web"),summary={active:campaigns.filter(item=>item.status==="active").length,scheduled:posts.filter(item=>item.status==="scheduled").length,published:posts.filter(item=>item.status==="published").length,failed:posts.filter(item=>["failed","uncertain","expired"].includes(item.status)).length};
  return <section className="status-center">
    <header className="status-center-head"><div><span className="eyebrow">WhatsApp Status</span><h1>动态发布</h1><p>按时区和时间窗管理动态内容队列；仅支持已绑定的 Windows/Web Agent。</p></div><div><button onClick={()=>void load()}><RefreshCw className={loading?"spin":""} size={15}/>刷新</button>{canManage&&<button className="primary-action" onClick={()=>setWizardDates(createWizardDates())}><Plus size={15}/>新建发布计划</button>}</div></header>
    <div className="status-summary"><Summary label="运行中的计划" value={summary.active}/><Summary label="等待发布" value={summary.scheduled}/><Summary label="已经发布" value={summary.published}/><Summary label="需要处理" value={summary.failed} tone="red"/></div>
    {!webAccounts.length&&<div className="status-warning">当前没有可用于发布动态的 Web Agent 账号；Cloud API 账号不支持此功能。</div>}
    <div className="status-campaign-strip">{campaigns.map(campaign=><article key={campaign.id} className={campaign.status}><button className="status-campaign-copy" onClick={()=>{setAccountId(campaign.account_id);setDisplayTimezone(campaign.timezone);}}><b>{campaign.name}</b><small>{campaign.account_name} · {campaign.timezone}</small><span>{campaign.published_count}/{campaign.post_count} 已发布 · {campaign.recipient_count} 位受众</span></button><em>{CAMPAIGN_STATUS[campaign.status]??campaign.status}</em>{canManage&&<div>{campaign.status==="active"?<button title="暂停" onClick={()=>void mutate(`/api/v1/status-campaigns/${campaign.id}/pause`)}><Pause size={13}/></button>:["draft","paused"].includes(campaign.status)?<button title={campaign.status==="draft"?"启用":"恢复"} onClick={()=>void mutate(`/api/v1/status-campaigns/${campaign.id}/${campaign.status==="draft"?"activate":"resume"}`)}><Play size={13}/></button>:null}{campaign.status!=="cancelled"&&campaign.status!=="completed"&&<button title="取消" onClick={()=>void mutate(`/api/v1/status-campaigns/${campaign.id}`,"DELETE")}><Trash2 size={13}/></button>}</div>}</article>)}</div>
    <div className="status-toolbar"><div className="status-view-tabs"><button className={view==="list"?"active":""} onClick={()=>setView("list")}><List size={14}/>列表</button><button className={view==="gantt"?"active":""} onClick={()=>setView("gantt")}><GanttChart size={14}/>甘特</button><button className={view==="calendar"?"active":""} onClick={()=>setView("calendar")}><CalendarDays size={14}/>日历</button></div><label className="status-search"><Search size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索计划或内容"/></label><select value={accountId} onChange={event=>setAccountId(event.target.value)}><option value="">全部 Web 账号</option>{webAccounts.map(account=><option value={account.id} key={account.id}>{account.name}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">全部状态</option>{Object.entries(STATUS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><input className="status-timezone" value={displayTimezone} onChange={event=>setDisplayTimezone(event.target.value)} aria-label="展示时区"/></div>
    {loading?<div className="status-empty"><RefreshCw className="spin" size={20}/>正在同步动态排期…</div>:view==="list"?<PostList posts={posts} timezone={displayTimezone} canManage={canManage} mutate={mutate}/>:view==="gantt"?<CampaignGantt campaigns={campaigns} posts={posts} cursor={cursor} onCursor={setCursor}/>:<StatusCalendar posts={posts} cursor={cursor} onCursor={setCursor} mode={calendarMode} onMode={setCalendarMode} timezone={displayTimezone}/>}
    {wizardDates&&<CampaignWizard accounts={webAccounts} initialDates={wizardDates} request={request} onToken={onToken} onClose={()=>setWizardDates(null)} onSaved={async text=>{setWizardDates(null);onToast(text);await load();}}/>}
  </section>;
}

function Summary({label,value,tone=""}:{label:string;value:number;tone?:string}){return <article className={tone}><span>{label}</span><b>{value}</b></article>;}
function PostList({posts,timezone,canManage,mutate}:{posts:Post[];timezone:string;canManage:boolean;mutate:(path:string,method?:string)=>Promise<void>}){return <div className="status-list-wrap"><table className="status-list"><thead><tr><th>内容</th><th>计划 / 账号</th><th>计划时间</th><th>受众</th><th>状态</th><th>操作</th></tr></thead><tbody>{posts.map(post=><tr key={post.id}><td><div className="status-content">{post.content_type==="image"?<ImageIcon size={15}/>:post.content_type==="video"?<Film size={15}/>:<Eye size={15}/>}<span><b>{post.text_content||post.file_name||"媒体动态"}</b><small>{post.content_type.toUpperCase()}{post.translation_target_language?` · 已翻译为 ${languageName(post.translation_target_language)}`:""}</small></span></div></td><td><b>{post.campaign_name}</b><small>{post.account_name} · {post.timezone}</small></td><td>{post.scheduled_at?formatInZone(post.scheduled_at,timezone):"尚未排期"}</td><td>{post.recipient_count}</td><td><span className={`status-badge ${post.status}`}>{STATUS[post.status]??post.status}</span>{post.last_error&&<small title={post.last_error}>{post.last_error}</small>}</td><td>{canManage&&<div className="status-row-actions">{["queued","scheduled"].includes(post.status)&&<button onClick={()=>void mutate(`/api/v1/status-posts/${post.id}/publish-now`)}><Send size={13}/>立即发布</button>}{["failed","uncertain","expired"].includes(post.status)&&<button onClick={()=>void mutate(`/api/v1/status-posts/${post.id}/retry`)}><RefreshCw size={13}/>重试</button>}</div>}</td></tr>)}{!posts.length&&<tr><td colSpan={6}><div className="status-empty">当前没有匹配的动态</div></td></tr>}</tbody></table></div>;}
function CampaignGantt({campaigns,posts,cursor,onCursor}:{campaigns:Campaign[];posts:Post[];cursor:Date;onCursor:(date:Date)=>void}){const start=startOfWeek(cursor),days=Array.from({length:28},(_,index)=>new Date(start.getTime()+index*DAY));return <div className="status-board"><BoardNav label={`${days[0].toLocaleDateString("zh-CN")} — ${days.at(-1)!.toLocaleDateString("zh-CN")}`} onPrev={()=>onCursor(new Date(cursor.getTime()-28*DAY))} onNext={()=>onCursor(new Date(cursor.getTime()+28*DAY))} onToday={()=>onCursor(new Date())}/><div className="status-gantt"><div className="status-gantt-head"><span>发布计划</span>{days.map(day=><b key={dateKey(day)}>{day.getMonth()+1}/{day.getDate()}</b>)}</div>{campaigns.map(campaign=>{const left=Math.max(0,Math.floor((new Date(`${campaign.start_date}T00:00:00Z`).getTime()-start.getTime())/DAY)),right=Math.min(days.length,Math.ceil((new Date(`${campaign.end_date}T23:59:59Z`).getTime()-start.getTime())/DAY)),markers=posts.filter(post=>post.campaign_id===campaign.id&&post.scheduled_at).map(post=>Math.max(0,Math.min(100,(new Date(post.scheduled_at!).getTime()-start.getTime())/(days.length*DAY)*100)));return <div className="status-gantt-row" key={campaign.id}><span><b>{campaign.name}</b><small>{campaign.account_name} · {campaign.timezone}</small></span><div>{right>0&&left<days.length&&<i className={campaign.status} style={{left:`${left/days.length*100}%`,width:`${Math.max(1,right-left)/days.length*100}%`}}><em style={{width:`${campaign.post_count?campaign.published_count/campaign.post_count*100:0}%`}}/></i>}{markers.map((marker,index)=><b className="status-slot-marker" style={{left:`${marker}%`}} key={index}/>)}</div></div>})}</div></div>;}
function StatusCalendar({posts,cursor,onCursor,mode,onMode,timezone}:{posts:Post[];cursor:Date;onCursor:(date:Date)=>void;mode:"month"|"week";onMode:(mode:"month"|"week")=>void;timezone:string}){const monthStart=new Date(cursor.getFullYear(),cursor.getMonth(),1),start=mode==="week"?startOfWeek(cursor):startOfWeek(monthStart),days=Array.from({length:mode==="week"?7:42},(_,index)=>new Date(start.getTime()+index*DAY));return <div className="status-board"><BoardNav label={cursor.toLocaleDateString("zh-CN",{year:"numeric",month:"long"})} onPrev={()=>onCursor(mode==="week"?new Date(cursor.getTime()-7*DAY):new Date(cursor.getFullYear(),cursor.getMonth()-1,1))} onNext={()=>onCursor(mode==="week"?new Date(cursor.getTime()+7*DAY):new Date(cursor.getFullYear(),cursor.getMonth()+1,1))} onToday={()=>onCursor(new Date())}><div className="status-calendar-mode"><button className={mode==="month"?"active":""} onClick={()=>onMode("month")}>月</button><button className={mode==="week"?"active":""} onClick={()=>onMode("week")}>周</button></div></BoardNav><div className={`status-calendar ${mode}`}>{days.map(day=>{const items=posts.filter(post=>post.scheduled_at&&zonedDayKey(post.scheduled_at,timezone)===dateKey(day));return <section key={dateKey(day)} className={dateKey(day)===dateKey(new Date())?"today":""}><header><b>{day.getDate()}</b><small>{"日一二三四五六"[day.getDay()]}</small></header>{items.map(post=><article className={post.status} key={post.id}><i/><span>{post.text_content||post.file_name||"媒体动态"}</span><time>{formatTime(post.scheduled_at!,timezone)}</time></article>)}</section>})}</div></div>;}
function BoardNav({label,onPrev,onNext,onToday,children}:{label:string;onPrev:()=>void;onNext:()=>void;onToday:()=>void;children?:ReactNode}){return <nav className="status-board-nav"><div><button onClick={onPrev}><ChevronLeft size={14}/></button><button onClick={onToday}>今天</button><button onClick={onNext}><ChevronRight size={14}/></button><b>{label}</b></div>{children}</nav>;}

function CampaignWizard({accounts,initialDates,request,onToken,onClose,onSaved}:{accounts:Account[];initialDates:WizardDates;request:(path:string,init?:RequestInit)=>Promise<RequestResult>;onToken:(token:string)=>void;onClose:()=>void;onSaved:(text:string)=>void}){
  const [step,setStep]=useState(1),[accountId,setAccountId]=useState(accounts[0]?.id??""),[name,setName]=useState(""),[items,setItems]=useState<DraftItem[]>([{id:crypto.randomUUID(),type:"text",text:"",sourceText:null,targetLanguage:"en",media:null,backgroundColor:"#147d52",font:0}]),[pickerItemId,setPickerItemId]=useState(""),[translatingItemId,setTranslatingItemId]=useState(""),[audienceMode,setAudienceMode]=useState<"all"|"manual"|"tags">("all"),[contacts,setContacts]=useState<Contact[]>([]),[contactIds,setContactIds]=useState<string[]>([]),[tags,setTags]=useState<Tag[]>([]),[tagIds,setTagIds]=useState<string[]>([]),[timezone,setTimezone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone),[startDate,setStartDate]=useState(initialDates.startDate),[endDate,setEndDate]=useState(initialDates.endDate),[weekdays,setWeekdays]=useState([1,2,3,4,5]),[dailyStart,setDailyStart]=useState("09:00"),[dailyEnd,setDailyEnd]=useState("18:00"),[intervalMinutes,setIntervalMinutes]=useState(180),[preview,setPreview]=useState<{capacity:number;overflow:number;slots:string[]}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(step!==3||!accountId)return;let active=true;void (async()=>{const all:Contact[]=[];let offset=0,hasMore=true;while(hasMore&&all.length<1000){const result=await request(`/api/v1/contacts?accountId=${accountId}&limit=100&offset=${offset}`);if(!result.response.ok)break;const body=await result.response.json() as {data:Contact[];hasMore:boolean;nextOffset:number};all.push(...body.data);hasMore=body.hasMore;offset=body.nextOffset;}const tagResult=await request("/api/v1/tags");if(!active)return;setContacts(all);if(tagResult.response.ok)setTags((await tagResult.response.json() as {data:Tag[]}).data);})();return()=>{active=false};},[step,accountId,request]);
  const schedule={timezone,startDate,endDate,activeWeekdays:weekdays,dailyStart,dailyEnd,intervalMinutes};
  async function previewSchedule(){setBusy(true);setError("");const result=await request("/api/v1/status-campaigns/preview-schedule",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...schedule,postCount:items.length})});const body=await result.response.json() as {capacity?:number;overflow?:number;slots?:string[];error?:string};setBusy(false);if(!result.response.ok){setError(errorText(body.error));return;}setPreview({capacity:body.capacity??0,overflow:body.overflow??0,slots:body.slots??[]});setStep(5);}
  async function translateItem(item:DraftItem){const source=(item.sourceText??item.text).trim();if(!source)return;setTranslatingItemId(item.id);setError("");try{const result=await request("/api/v1/translations/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text:source,targetLanguage:item.targetLanguage})});onToken(result.token);const body=await result.response.json().catch(()=>({})) as {translatedText?:string;message?:string;error?:string};if(!result.response.ok||!body.translatedText)throw new Error(body.message??errorText(body.error));setItems(all=>all.map(value=>value.id===item.id?{...value,text:body.translatedText!,sourceText:source}:value));}catch(reason){setError(reason instanceof Error?reason.message:"动态翻译失败");}finally{setTranslatingItemId("");}}
  async function submit(){setBusy(true);setError("");try{const create=await request("/api/v1/status-campaigns",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clientCampaignId:crypto.randomUUID(),accountId,name,...schedule,audience:{mode:audienceMode,contactIds,tagIds}})}),campaign=await create.response.json() as {id?:string;error?:string};if(!create.response.ok||!campaign.id)throw new Error(errorText(campaign.error));const posts=items.map(item=>({clientPostId:crypto.randomUUID(),type:item.type,text:item.text||undefined,translationSourceText:item.sourceText??undefined,translationTargetLanguage:item.sourceText?item.targetLanguage:undefined,mediaId:item.media?.id,backgroundColor:item.type==="text"?item.backgroundColor:undefined,font:item.type==="text"?item.font:undefined}));const postResult=await request(`/api/v1/status-campaigns/${campaign.id}/posts`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({items:posts})}),postBody=await postResult.response.json().catch(()=>({})) as {error?:string};if(!postResult.response.ok)throw new Error(errorText(postBody.error));const activate=await request(`/api/v1/status-campaigns/${campaign.id}/activate`,{method:"POST"}),activateBody=await activate.response.json().catch(()=>({})) as {error?:string};if(!activate.response.ok)throw new Error(errorText(activateBody.error));onSaved("动态发布计划已启用");}catch(reason){setError(reason instanceof Error?reason.message:"计划创建失败");}finally{setBusy(false);}}
  const validStep=step===1?Boolean(accountId&&name.trim()):step===2?items.length>0&&items.every(item=>item.type==="text"?item.text.trim():item.media):step===3?audienceMode==="all"||(audienceMode==="manual"?contactIds.length>0:tagIds.length>0):step===4?Boolean(timezone&&startDate&&endDate&&weekdays.length&&dailyStart<dailyEnd&&intervalMinutes>0):true;
  const pickerItem=items.find(item=>item.id===pickerItemId)??null;
  return <><div className="status-wizard-backdrop"><section className="status-wizard"><header><div><span>步骤 {step} / 5</span><h2>新建动态发布计划</h2></div><button onClick={onClose} disabled={busy}><X size={16}/></button></header><div className="status-wizard-progress">{[1,2,3,4,5].map(value=><i className={value<=step?"active":""} key={value}/>)}</div><main>
    {step===1&&<><h3>选择发布账号</h3><p>每个计划只使用一个 Web Agent 账号。</p><label>计划名称<input value={name} onChange={event=>setName(event.target.value)} maxLength={120} autoFocus placeholder="例如：八月新品动态"/></label><label>WhatsApp 账号<select value={accountId} onChange={event=>{setAccountId(event.target.value);setItems(all=>all.map(item=>({...item,media:null})));}}>{accounts.map(account=><option value={account.id} key={account.id}>{account.name} · {account.status==="online"?"在线":"离线"}</option>)}</select></label></>}
    {step===2&&<><div className="status-step-heading"><div><h3>建立内容队列</h3><p>按顺序发布文字、图片或 MP4 视频；每条文字或媒体说明都可以单独翻译。</p></div><span>{items.length} 条内容</span></div><div className="status-draft-list">{items.map((item,index)=><article className={item.type} key={item.id}><b className="status-draft-index">{index+1}</b><select aria-label={`第 ${index+1} 条内容类型`} value={item.type} onChange={event=>setItems(all=>all.map(value=>value.id===item.id?{...value,type:event.target.value as DraftItem["type"],media:null}:value))}><option value="text">文字</option><option value="image">图片</option><option value="video">视频</option></select>{item.type==="text"?<><textarea value={item.text} onChange={event=>setItems(all=>all.map(value=>value.id===item.id?{...value,text:event.target.value,sourceText:null}:value))} placeholder="输入动态文字"/><input aria-label="文字动态背景色" type="color" value={item.backgroundColor} onChange={event=>setItems(all=>all.map(value=>value.id===item.id?{...value,backgroundColor:event.target.value}:value))}/></>:<><button type="button" className={`status-media-select ${item.media?"selected":""}`} onClick={()=>setPickerItemId(item.id)}>{item.media?<MediaImagePreview mediaId={item.media.id} mimeType={item.media.mimeType} alt={item.media.fileName} request={request} onToken={onToken} className="status-media-thumb"/>:<span className="status-media-placeholder"><UploadCloud size={18}/></span>}<span><b>{item.media?.fileName||`选择${item.type==="image"?"图片":"MP4 视频"}`}</b><small>{item.media?`${formatMediaSize(item.media.size)} · 点击更换`:"从媒体与附件选择，或在弹窗中上传"}</small></span></button><textarea className="status-media-caption" value={item.text} onChange={event=>setItems(all=>all.map(value=>value.id===item.id?{...value,text:event.target.value,sourceText:null}:value))} placeholder="添加动态说明（可选）"/></>}<TranslationTools item={item} busy={translatingItemId===item.id} onTargetLanguage={targetLanguage=>setItems(all=>all.map(value=>value.id===item.id?{...value,targetLanguage}:value))} onTranslate={()=>void translateItem(item)} onRestore={()=>setItems(all=>all.map(value=>value.id===item.id&&value.sourceText?{...value,text:value.sourceText,sourceText:null}:value))}/><button className="status-draft-remove" aria-label={`删除第 ${index+1} 条内容`} onClick={()=>setItems(all=>all.filter(value=>value.id!==item.id))} disabled={items.length===1}><Trash2 size={14}/></button></article>)}</div><button className="status-add-item" onClick={()=>setItems(all=>[...all,{id:crypto.randomUUID(),type:"text",text:"",sourceText:null,targetLanguage:"en",media:null,backgroundColor:"#147d52",font:0}])}><Plus size={14}/>添加一条内容</button></>}
    {step===3&&<><h3>选择可见受众</h3><p>启用计划时会保存受众快照，后续联系人变化不会影响本计划。</p><div className="status-audience-modes"><label><input type="radio" checked={audienceMode==="all"} onChange={()=>setAudienceMode("all")}/>全部已知联系人</label><label><input type="radio" checked={audienceMode==="manual"} onChange={()=>setAudienceMode("manual")}/>手动选择</label><label><input type="radio" checked={audienceMode==="tags"} onChange={()=>setAudienceMode("tags")}/>按会话标签</label></div>{audienceMode==="manual"&&<div className="status-recipient-grid">{contacts.map(contact=><label key={contact.id}><input type="checkbox" checked={contactIds.includes(contact.id)} onChange={()=>setContactIds(all=>all.includes(contact.id)?all.filter(id=>id!==contact.id):[...all,contact.id])}/><span>{contact.name}<small>{contact.phone}</small></span></label>)}</div>}{audienceMode==="tags"&&<div className="status-recipient-grid">{tags.map(tag=><label key={tag.id}><input type="checkbox" checked={tagIds.includes(tag.id)} onChange={()=>setTagIds(all=>all.includes(tag.id)?all.filter(id=>id!==tag.id):[...all,tag.id])}/><i style={{background:tag.color}}/>{tag.name}</label>)}</div>}</>}
    {step===4&&<><h3>设置排期规则</h3><p>所有输入按计划时区解释，每个有效日期都从每日开始时间重新排列。</p><div className="status-schedule-grid"><label>时区<input value={timezone} onChange={event=>setTimezone(event.target.value)} placeholder="Asia/Shanghai"/></label><label>间隔（分钟）<input type="number" min={1} max={10080} value={intervalMinutes} onChange={event=>setIntervalMinutes(Number(event.target.value))}/></label><label>开始日期<input type="date" value={startDate} onChange={event=>setStartDate(event.target.value)}/></label><label>结束日期<input type="date" value={endDate} onChange={event=>setEndDate(event.target.value)}/></label><label>每日开始<input type="time" value={dailyStart} onChange={event=>setDailyStart(event.target.value)}/></label><label>每日结束<input type="time" value={dailyEnd} onChange={event=>setDailyEnd(event.target.value)}/></label></div><div className="status-weekdays">{["日","一","二","三","四","五","六"].map((label,index)=><button className={weekdays.includes(index)?"active":""} key={label} onClick={()=>setWeekdays(all=>all.includes(index)?all.filter(day=>day!==index):[...all,index])}>周{label}</button>)}</div></>}
    {step===5&&preview&&<><h3>确认并启用计划</h3><div className="status-preview-summary"><span><b>{items.length}</b> 条内容</span><span><b>{preview.capacity}</b> 个可用槽位</span><span><b>{audienceMode==="all"?"全部":audienceMode==="manual"?contactIds.length:tagIds.length}</b> {audienceMode==="tags"?"个标签":"位/范围受众"}</span></div>{preview.overflow>0?<div className="status-error">当前时间范围少 {preview.overflow} 个槽位，请返回调整。</div>:<div className="status-slot-preview">{preview.slots.slice(0,20).map(slot=><span key={slot}><Clock3 size={12}/>{formatInZone(slot,timezone)}</span>)}</div>}</>}
    {error&&<div className="status-error">{error}</div>}
  </main><footer><button onClick={step===1?onClose:()=>setStep(value=>value-1)} disabled={busy}>{step===1?"取消":"上一步"}</button>{step<4?<button className="primary-action" disabled={!validStep||busy} onClick={()=>setStep(value=>value+1)}>下一步</button>:step===4?<button className="primary-action" disabled={!validStep||busy} onClick={()=>void previewSchedule()}>{busy?"正在计算…":"预览排期"}</button>:<button className="primary-action" disabled={Boolean(preview?.overflow)||busy} onClick={()=>void submit()}>{busy?"正在创建…":"创建并启用"}</button>}</footer></section></div>{pickerItem&&<ProductImageMediaDialog className="status-media-picker" request={request} onToken={onToken} onClose={()=>setPickerItemId("")} onSelect={asset=>{setItems(all=>all.map(item=>item.id===pickerItem.id?{...item,media:asset}:item));setPickerItemId("");}} libraryPath={`/api/v1/media?accountId=${encodeURIComponent(accountId)}&limit=100`} uploadPath={`/api/v1/media?accountId=${encodeURIComponent(accountId)}`} title={`选择动态${pickerItem.type==="image"?"图片":"视频"}`} description={`复用该 WhatsApp 账号媒体与附件中的${pickerItem.type==="image"?"图片":" MP4 视频"}，或上传新文件。`} actionLabel="使用所选媒体" acceptedMimeTypes={pickerItem.type==="image"?["image/jpeg","image/png","image/webp"]:["video/mp4"]}/>}</>;
}

function TranslationTools({item,busy,onTargetLanguage,onTranslate,onRestore}:{item:DraftItem;busy:boolean;onTargetLanguage:(value:string)=>void;onTranslate:()=>void;onRestore:()=>void}){return <div className="status-translation-tools"><span><Languages size={14}/>{item.sourceText?`已翻译为 ${languageName(item.targetLanguage)}`:"AI 翻译"}</span><LanguagePicker value={item.targetLanguage} onChange={onTargetLanguage} label="搜索动态目标语言"/><button type="button" disabled={busy||!item.text.trim()} onClick={onTranslate}>{busy?<><RefreshCw className="spin" size={13}/>翻译中…</>:<><Languages size={13}/>{item.sourceText?"重新翻译":"翻译"}</>}</button>{item.sourceText&&<button type="button" onClick={onRestore}>恢复原文</button>}</div>;}
function errorText(code?:string){return({supervisor_required:"只有主管或管理员可以管理动态",status_web_account_required:"仅 Web Agent 账号支持动态",agent_upgrade_required:"Windows Agent 尚未升级到支持动态的版本",status_audience_empty:"所选范围内没有有效 WhatsApp 联系人",status_audience_too_large:"受众数量超过系统上限",schedule_capacity_exceeded:"排期槽位不足",invalid_schedule_date:"排期日期无效，请重新选择开始和结束日期",invalid_timezone:"时区无效",campaign_not_activated:"计划尚未启用",translation_not_configured:"AI 翻译服务尚未配置",translation_failed:"动态翻译失败"} as Record<string,string>)[code??""]??code??"操作失败";}
function createWizardDates():WizardDates{const start=new Date(),end=new Date(start);end.setDate(end.getDate()+14);return{startDate:start.toISOString().slice(0,10),endDate:end.toISOString().slice(0,10)};}
function formatMediaSize(size:number){if(size<1024)return`${size} B`;if(size<1048576)return`${(size/1024).toFixed(1)} KB`;return`${(size/1048576).toFixed(1)} MB`;}
function formatInZone(value:string,timeZone:string){try{return new Intl.DateTimeFormat("zh-CN",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(value));}catch{return new Date(value).toLocaleString("zh-CN");}}
function formatTime(value:string,timeZone:string){try{return new Intl.DateTimeFormat("zh-CN",{timeZone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(value));}catch{return new Date(value).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"});}}
function zonedDayKey(value:string,timeZone:string){try{const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(value)),get=(type:string)=>parts.find(part=>part.type===type)?.value;return`${get("year")}-${get("month")}-${get("day")}`;}catch{return value.slice(0,10);}}
function dateKey(value:Date){return`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;}
function startOfWeek(value:Date){const result=new Date(value.getFullYear(),value.getMonth(),value.getDate());result.setDate(result.getDate()-result.getDay());return result;}
