ALTER TABLE order_settings
  ADD COLUMN IF NOT EXISTS text_template jsonb DEFAULT '{"version":1,"blocks":[{"id":"order-header","type":"orderHeader","label":"Order","bold":true,"blankAfter":true},{"id":"items","type":"itemList","label":"Items:","blankAfter":true},{"id":"fees","type":"feeList","label":"Additional fees:","blankAfter":true},{"id":"total","type":"total","label":"Total:","bold":true},{"id":"notes","type":"notes","label":"Notes:"}]}'::jsonb,
  ADD COLUMN IF NOT EXISTS image_template jsonb DEFAULT '{"version":1,"blocks":[{"id":"order-header","type":"orderHeader","label":"Order","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"items","type":"itemList","label":"Items:","fontSize":"medium","textColor":"#20372D","backgroundColor":"#F6F9F7","align":"left","showProductImages":true,"imageSize":"medium"},{"id":"fees","type":"feeList","label":"Additional fees:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FAFCFB","align":"left"},{"id":"total","type":"total","label":"Total:","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"notes","type":"notes","label":"Notes:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FFFAF0","align":"left"}]}'::jsonb;

UPDATE order_settings
SET text_template=COALESCE(text_template, '{"version":1,"blocks":[{"id":"order-header","type":"orderHeader","label":"Order","bold":true,"blankAfter":true},{"id":"items","type":"itemList","label":"Items:","blankAfter":true},{"id":"fees","type":"feeList","label":"Additional fees:","blankAfter":true},{"id":"total","type":"total","label":"Total:","bold":true},{"id":"notes","type":"notes","label":"Notes:"}]}'::jsonb),
    image_template=COALESCE(image_template, '{"version":1,"blocks":[{"id":"order-header","type":"orderHeader","label":"Order","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"items","type":"itemList","label":"Items:","fontSize":"medium","textColor":"#20372D","backgroundColor":"#F6F9F7","align":"left","showProductImages":true,"imageSize":"medium"},{"id":"fees","type":"feeList","label":"Additional fees:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FAFCFB","align":"left"},{"id":"total","type":"total","label":"Total:","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"notes","type":"notes","label":"Notes:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FFFAF0","align":"left"}]}'::jsonb)
WHERE text_template IS NULL OR image_template IS NULL;

ALTER TABLE order_settings
  ALTER COLUMN text_template SET NOT NULL,
  ALTER COLUMN image_template SET NOT NULL;
