ALTER TABLE order_settings
  ADD COLUMN IF NOT EXISTS sc_template jsonb,
  ADD COLUMN IF NOT EXISTS pi_template jsonb,
  ADD COLUMN IF NOT EXISTS ci_template jsonb;

UPDATE order_settings
SET sc_template=COALESCE(sc_template, jsonb_set(jsonb_set(COALESCE(pdf_template,'{}'::jsonb), '{blocks,0,label}', '"Sales Contract"'::jsonb), '{blocks,0,statusLabels}', '{"quotation":"Sales Contract","pending_confirmation":"Sales Contract","pending_payment":"Sales Contract","paid":"Sales Contract","processing":"Sales Contract","shipped":"Sales Contract","completed":"Sales Contract","cancelled":"Sales Contract"}'::jsonb)),
    pi_template=COALESCE(pi_template, jsonb_set(jsonb_set(COALESCE(pdf_template,'{}'::jsonb), '{blocks,0,label}', '"Proforma Invoice"'::jsonb), '{blocks,0,statusLabels}', '{"quotation":"Proforma Invoice","pending_confirmation":"Proforma Invoice","pending_payment":"Proforma Invoice","paid":"Proforma Invoice","processing":"Proforma Invoice","shipped":"Proforma Invoice","completed":"Proforma Invoice","cancelled":"Proforma Invoice"}'::jsonb)),
    ci_template=COALESCE(ci_template, jsonb_set(jsonb_set(COALESCE(pdf_template,'{}'::jsonb), '{blocks,0,label}', '"Commercial Invoice"'::jsonb), '{blocks,0,statusLabels}', '{"quotation":"Commercial Invoice","pending_confirmation":"Commercial Invoice","pending_payment":"Commercial Invoice","paid":"Commercial Invoice","processing":"Commercial Invoice","shipped":"Commercial Invoice","completed":"Commercial Invoice","cancelled":"Commercial Invoice"}'::jsonb));

ALTER TABLE order_settings
  ALTER COLUMN sc_template SET DEFAULT '{"version":1,"blocks":[{"id":"order-header","type":"orderHeader","label":"Sales Contract","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"items","type":"itemList","label":"Items:","itemTemplate":"{{index}}. {{title}} x {{quantity}} - {{price}} each - {{subtotal}}","fontSize":"medium","textColor":"#20372D","backgroundColor":"#F6F9F7","align":"left","showProductImages":true,"imageSize":"medium"},{"id":"fees","type":"feeList","label":"Additional fees:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FAFCFB","align":"left"},{"id":"total","type":"total","label":"Total:","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"payment-summary","type":"paymentSummary","label":"Payment:","fontSize":"medium","textColor":"#20372D","backgroundColor":"#EEF6F2","align":"left"},{"id":"notes","type":"notes","label":"Notes:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FFFAF0","align":"left"}]}'::jsonb,
  ALTER COLUMN pi_template SET DEFAULT '{"version":1,"blocks":[{"id":"order-header","type":"orderHeader","label":"Proforma Invoice","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"items","type":"itemList","label":"Items:","itemTemplate":"{{index}}. {{title}} x {{quantity}} - {{price}} each - {{subtotal}}","fontSize":"medium","textColor":"#20372D","backgroundColor":"#F6F9F7","align":"left","showProductImages":true,"imageSize":"medium"},{"id":"fees","type":"feeList","label":"Additional fees:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FAFCFB","align":"left"},{"id":"total","type":"total","label":"Total:","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"payment-summary","type":"paymentSummary","label":"Payment:","fontSize":"medium","textColor":"#20372D","backgroundColor":"#EEF6F2","align":"left"},{"id":"notes","type":"notes","label":"Notes:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FFFAF0","align":"left"}]}'::jsonb,
  ALTER COLUMN ci_template SET DEFAULT '{"version":1,"blocks":[{"id":"order-header","type":"orderHeader","label":"Commercial Invoice","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"items","type":"itemList","label":"Items:","itemTemplate":"{{index}}. {{title}} x {{quantity}} - {{price}} each - {{subtotal}}","fontSize":"medium","textColor":"#20372D","backgroundColor":"#F6F9F7","align":"left","showProductImages":true,"imageSize":"medium"},{"id":"fees","type":"feeList","label":"Additional fees:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FAFCFB","align":"left"},{"id":"total","type":"total","label":"Total:","fontSize":"large","textColor":"#FFFFFF","backgroundColor":"#153F2F","align":"left"},{"id":"payment-summary","type":"paymentSummary","label":"Payment:","fontSize":"medium","textColor":"#20372D","backgroundColor":"#EEF6F2","align":"left"},{"id":"notes","type":"notes","label":"Notes:","fontSize":"small","textColor":"#20372D","backgroundColor":"#FFFAF0","align":"left"}]}'::jsonb;

UPDATE order_settings SET sc_template=COALESCE(sc_template,pdf_template), pi_template=COALESCE(pi_template,pdf_template), ci_template=COALESCE(ci_template,pdf_template) WHERE singleton=true;

ALTER TABLE order_settings
  ALTER COLUMN sc_template SET NOT NULL,
  ALTER COLUMN pi_template SET NOT NULL,
  ALTER COLUMN ci_template SET NOT NULL;
