import type {FastifyInstance} from "fastify";
import {pool,transaction} from "./db.js";
import {authenticate,canAccessAccount,type Principal} from "./auth.js";
import {ensureProactiveOutreachTables,normalizeProactiveMessageTemplates,scanProactiveOutreach,suppressProactiveForContact} from "./proactive-outreach.js";
const elevated=(role:string|undefined)=>role==="admin"||role==="supervisor";
async function proactiveAccountIds(principal:Principal|undefined):Promise<string[]|null>{
  if(!principal)return[];
  if(principal.kind==="api_key")return principal.accountIds??null;
  if(principal.role==="admin")return null;
  return(await pool.query("SELECT account_id FROM account_permissions WHERE user_id=$1 AND can_read",[principal.id])).rows.map(row=>String(row.account_id));
}
export async function registerProactiveRoutes(app:FastifyInstance){await ensureProactiveOutreachTables();
  app.get("/api/v1/proactive-outreach/jobs",{preHandler:authenticate},async(request,reply)=>{const query=request.query as {accountId?:string;q?:string;limit?:string;offset?:string};const accountIds=await proactiveAccountIds(request.principal);if(query.accountId&&accountIds!==null&&!accountIds.includes(query.accountId))return reply.code(403).send({error:"account_forbidden"});const limit=Math.min(200,Math.max(1,Number(query.limit)||100)),offset=Math.max(0,Number(query.offset)||0),result=await pool.query(`SELECT j.id,j.account_id,j.contact_id,j.conversation_id,j.trigger_kind,j.planned_at,j.state,j.created_at,a.display_name account_name,COALESCE(NULLIF(c.alias,''),c.display_name,c.phone_e164) contact_name,COUNT(*) OVER()::int total_count FROM proactive_outreach_jobs j JOIN channel_accounts a ON a.id=j.account_id JOIN contacts c ON c.id=j.contact_id WHERE ($1::uuid IS NULL OR j.account_id=$1) AND ($2::uuid[] IS NULL OR j.account_id=ANY($2)) AND j.state IN ('pending','processing') AND ($3::text IS NULL OR c.alias ILIKE '%'||$3||'%' OR c.display_name ILIKE '%'||$3||'%' OR c.phone_e164 ILIKE '%'||$3||'%' OR a.display_name ILIKE '%'||$3||'%' OR j.trigger_kind ILIKE '%'||$3||'%') ORDER BY j.planned_at,j.id LIMIT $4 OFFSET $5`,[query.accountId??null,accountIds,query.q?.trim()||null,limit,offset]);return{items:result.rows.map(row=>({id:String(row.id),accountId:String(row.account_id),contactId:String(row.contact_id),conversationId:row.conversation_id?String(row.conversation_id):null,triggerKind:String(row.trigger_kind),plannedAt:new Date(String(row.planned_at)).toISOString(),state:String(row.state),createdAt:new Date(String(row.created_at)).toISOString(),accountName:String(row.account_name),contactName:String(row.contact_name??"")})),total:Number(result.rows[0]?.total_count??0),hasMore:offset+Number(result.rowCount??0)<Number(result.rows[0]?.total_count??0)};});
  app.get("/api/v1/accounts/:id/proactive-outreach",{preHandler:authenticate},async(request,reply)=>{const {id}=request.params as {id:string};if(!canAccessAccount(request.principal,id))return reply.code(404).send({error:"not_found"});const settings=await pool.query("SELECT * FROM proactive_outreach_settings WHERE account_id=$1",[id]);const stats=await pool.query("SELECT event_type,count(*)::int count FROM proactive_outreach_events WHERE account_id=$1 AND created_at>now()-interval '365 days' GROUP BY event_type",[id]);const upcoming=await pool.query("SELECT j.id,j.contact_id,j.trigger_kind,j.planned_at,j.state,COALESCE(NULLIF(c.alias,''),c.display_name,c.phone_e164) contact_name FROM proactive_outreach_jobs j JOIN contacts c ON c.id=j.contact_id WHERE j.account_id=$1 AND j.state IN ('pending','processing') ORDER BY j.planned_at LIMIT 50",[id]);return{...(settings.rows[0]??{account_id:id,enabled:false,max_touches_per_year:5,max_touches_per_day:20,local_send_start:"10:00",local_send_end:"17:00",country_holidays:{},message_templates:{}}),stats:stats.rows,upcoming:upcoming.rows};});
  app.put("/api/v1/accounts/:id/proactive-outreach",{preHandler:authenticate},async(request,reply)=>{if(!elevated(request.principal?.role))return reply.code(403).send({error:"supervisor_required"});const {id}=request.params as {id:string};if(!canAccessAccount(request.principal,id))return reply.code(404).send({error:"not_found"});const body=(request.body??{}) as Record<string,unknown>,max=Number(body.maxTouchesPerYear??5),dailyMax=Number(body.maxTouchesPerDay??20),start=String(body.localSendStart??"10:00"),end=String(body.localSendEnd??"17:00"),templates=body.messageTemplates??{};if(!Number.isInteger(max)||max<1||max>12||!Number.isInteger(dailyMax)||dailyMax<1||dailyMax>500||!/^\d\d:\d\d$/.test(start)||!/^\d\d:\d\d$/.test(end)||(body.messageTemplates!==undefined&&!normalizeProactiveMessageTemplates(templates).length))return reply.code(400).send({error:"invalid_request"});await pool.query("INSERT INTO proactive_outreach_settings(account_id,enabled,max_touches_per_year,max_touches_per_day,local_send_start,local_send_end,country_holidays,message_templates) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(account_id) DO UPDATE SET enabled=EXCLUDED.enabled,max_touches_per_year=EXCLUDED.max_touches_per_year,max_touches_per_day=EXCLUDED.max_touches_per_day,local_send_start=EXCLUDED.local_send_start,local_send_end=EXCLUDED.local_send_end,country_holidays=EXCLUDED.country_holidays,message_templates=EXCLUDED.message_templates,updated_at=now()",[id,Boolean(body.enabled),max,dailyMax,start,end,JSON.stringify(body.countryHolidays??{}),JSON.stringify(templates)]);return reply.code(204).send();});
  app.get("/api/v1/contacts/:id/proactive-outreach",{preHandler:authenticate},async(request,reply)=>{const {id}=request.params as {id:string};const contact=await pool.query("SELECT account_id,proactive_suppressed_at,proactive_suppression_reason,country_code FROM contacts WHERE id=$1",[id]);if(!contact.rowCount||!canAccessAccount(request.principal,contact.rows[0].account_id))return reply.code(404).send({error:"not_found"});const events=await pool.query("SELECT * FROM proactive_outreach_events WHERE contact_id=$1 ORDER BY created_at DESC LIMIT 100",[id]);return{...contact.rows[0],events:events.rows};});
  app.put("/api/v1/contacts/:id/proactive-outreach",{preHandler:authenticate},async(request,reply)=>{if(!elevated(request.principal?.role))return reply.code(403).send({error:"supervisor_required"});const {id}=request.params as {id:string};const contact=await pool.query("SELECT account_id FROM contacts WHERE id=$1",[id]);if(!contact.rowCount||!canAccessAccount(request.principal,contact.rows[0].account_id))return reply.code(404).send({error:"not_found"});const body=(request.body??{}) as {suppressed?:boolean;reason?:string};await transaction(async client=>{if(body.suppressed!==false)await suppressProactiveForContact(client,id,String(body.reason??"manual_pause").slice(0,200));else{await client.query("UPDATE contacts SET proactive_suppressed_at=NULL,proactive_suppression_reason=NULL,updated_at=now() WHERE id=$1",[id]);await client.query("INSERT INTO proactive_outreach_events(account_id,contact_id,event_type,reason) VALUES($1,$2,'restored','manual_restore')",[contact.rows[0].account_id,id]);}});return reply.code(204).send();});
  app.post("/api/v1/accounts/:id/proactive-outreach/scan",{preHandler:authenticate},async(request,reply)=>{if(!elevated(request.principal?.role))return reply.code(403).send({error:"supervisor_required"});const {id}=request.params as {id:string};if(!canAccessAccount(request.principal,id))return reply.code(404).send({error:"not_found"});await scanProactiveOutreach();return reply.code(202).send();});
}
