import type {FastifyInstance} from "fastify";
import {pool,transaction} from "./db.js";
import {authenticate,canAccessAccount} from "./auth.js";
import {ensureProactiveOutreachTables,scanProactiveOutreach,suppressProactiveForContact} from "./proactive-outreach.js";
const elevated=(role:string|undefined)=>role==="admin"||role==="supervisor";
export async function registerProactiveRoutes(app:FastifyInstance){await ensureProactiveOutreachTables();
  app.get("/api/v1/accounts/:id/proactive-outreach",{preHandler:authenticate},async(request,reply)=>{const {id}=request.params as {id:string};if(!canAccessAccount(request.principal,id))return reply.code(404).send({error:"not_found"});const settings=await pool.query("SELECT * FROM proactive_outreach_settings WHERE account_id=$1",[id]);const stats=await pool.query("SELECT event_type,count(*)::int count FROM proactive_outreach_events WHERE account_id=$1 AND created_at>now()-interval '365 days' GROUP BY event_type",[id]);const upcoming=await pool.query("SELECT j.id,j.contact_id,j.trigger_kind,j.planned_at,j.state,COALESCE(NULLIF(c.alias,''),c.display_name,c.phone_e164) contact_name FROM proactive_outreach_jobs j JOIN contacts c ON c.id=j.contact_id WHERE j.account_id=$1 AND j.state IN ('pending','processing') ORDER BY j.planned_at LIMIT 50",[id]);return{...(settings.rows[0]??{account_id:id,enabled:false,max_touches_per_year:5,local_send_start:"10:00",local_send_end:"17:00",country_holidays:{},cloud_templates:{}}),stats:stats.rows,upcoming:upcoming.rows};});
  app.put("/api/v1/accounts/:id/proactive-outreach",{preHandler:authenticate},async(request,reply)=>{if(!elevated(request.principal?.role))return reply.code(403).send({error:"supervisor_required"});const {id}=request.params as {id:string};if(!canAccessAccount(request.principal,id))return reply.code(404).send({error:"not_found"});const body=(request.body??{}) as Record<string,unknown>,max=Number(body.maxTouchesPerYear??5),start=String(body.localSendStart??"10:00"),end=String(body.localSendEnd??"17:00");if(!Number.isInteger(max)||max<1||max>12||!/^\d\d:\d\d$/.test(start)||!/^\d\d:\d\d$/.test(end))return reply.code(400).send({error:"invalid_request"});await pool.query("INSERT INTO proactive_outreach_settings(account_id,enabled,max_touches_per_year,local_send_start,local_send_end,country_holidays,cloud_templates) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(account_id) DO UPDATE SET enabled=EXCLUDED.enabled,max_touches_per_year=EXCLUDED.max_touches_per_year,local_send_start=EXCLUDED.local_send_start,local_send_end=EXCLUDED.local_send_end,country_holidays=EXCLUDED.country_holidays,cloud_templates=EXCLUDED.cloud_templates,updated_at=now()",[id,Boolean(body.enabled),max,start,end,JSON.stringify(body.countryHolidays??{}),JSON.stringify(body.cloudTemplates??{})]);return reply.code(204).send();});
  app.get("/api/v1/contacts/:id/proactive-outreach",{preHandler:authenticate},async(request,reply)=>{const {id}=request.params as {id:string};const contact=await pool.query("SELECT account_id,proactive_suppressed_at,proactive_suppression_reason,country_code FROM contacts WHERE id=$1",[id]);if(!contact.rowCount||!canAccessAccount(request.principal,contact.rows[0].account_id))return reply.code(404).send({error:"not_found"});const events=await pool.query("SELECT * FROM proactive_outreach_events WHERE contact_id=$1 ORDER BY created_at DESC LIMIT 100",[id]);return{...contact.rows[0],events:events.rows};});
  app.put("/api/v1/contacts/:id/proactive-outreach",{preHandler:authenticate},async(request,reply)=>{if(!elevated(request.principal?.role))return reply.code(403).send({error:"supervisor_required"});const {id}=request.params as {id:string};const contact=await pool.query("SELECT account_id FROM contacts WHERE id=$1",[id]);if(!contact.rowCount||!canAccessAccount(request.principal,contact.rows[0].account_id))return reply.code(404).send({error:"not_found"});const body=(request.body??{}) as {suppressed?:boolean;reason?:string};await transaction(async client=>{if(body.suppressed!==false)await suppressProactiveForContact(client,id,String(body.reason??"manual_pause").slice(0,200));else{await client.query("UPDATE contacts SET proactive_suppressed_at=NULL,proactive_suppression_reason=NULL,updated_at=now() WHERE id=$1",[id]);await client.query("INSERT INTO proactive_outreach_events(account_id,contact_id,event_type,reason) VALUES($1,$2,'restored','manual_restore')",[contact.rows[0].account_id,id]);}});return reply.code(204).send();});
  app.post("/api/v1/accounts/:id/proactive-outreach/scan",{preHandler:authenticate},async(request,reply)=>{if(!elevated(request.principal?.role))return reply.code(403).send({error:"supervisor_required"});const {id}=request.params as {id:string};if(!canAccessAccount(request.principal,id))return reply.code(404).send({error:"not_found"});await scanProactiveOutreach();return reply.code(202).send();});
}