import type {FastifyInstance,FastifyReply,FastifyRequest} from "fastify";
import {pool,transaction} from "./db.js";
import {authenticate,canAccessAccount,type Principal} from "./auth.js";
import {accountTaskSettingsSchema,taskCreateSchema,taskDraftResolveSchema,taskRescheduleSchema,taskUpdateSchema} from "./schemas.js";
import {completeGeneralTask,dispatchTask,effectiveTaskTools,generateTaskDraft,TASK_TOOLS} from "./task-engine.js";

const elevated=(principal:Principal|undefined)=>["admin","supervisor"].includes(principal?.role??"");
async function canAccessTaskAccount(principal:Principal|undefined,accountId:string){if(!principal)return false;if(principal.kind==="api_key")return canAccessAccount(principal,accountId);if(principal.role==="admin")return true;const allowed=await pool.query("SELECT 1 FROM account_permissions WHERE account_id=$1 AND user_id=$2 AND can_read LIMIT 1",[accountId,principal.id]);return Boolean(allowed.rowCount);}
async function taskAccountIds(principal:Principal|undefined):Promise<string[]|null>{if(!principal)return[];if(principal.kind==="api_key")return principal.accountIds??null;if(principal.role==="admin")return null;return(await pool.query("SELECT account_id FROM account_permissions WHERE user_id=$1 AND can_read",[principal.id])).rows.map(row=>String(row.account_id));}
const rowInput=(row:Record<string,unknown>)=>({accountId:String(row.account_id),contactId:row.contact_id?String(row.contact_id):null,conversationId:row.conversation_id?String(row.conversation_id):null,assignedUserId:row.assigned_user_id?String(row.assigned_user_id):null,kind:row.kind,title:String(row.title),description:String(row.description??""),status:row.status,progress:Number(row.progress),startAt:new Date(String(row.start_at)).toISOString(),dueAt:new Date(String(row.due_at)).toISOString(),sendAt:row.send_at?new Date(String(row.send_at)).toISOString():null,sendMode:row.send_mode,recurrence:row.recurrence??null,personaOverride:row.persona_override?String(row.persona_override):null,toolOverrides:row.tool_overrides??null,dependencyIds:[]});
async function accountDefaults(accountId:string){const result=await pool.query("SELECT COALESCE(default_tools,'{}') default_tools FROM account_task_settings WHERE account_id=$1",[accountId]);return effectiveTaskTools(result.rows[0]?.default_tools,undefined);}
async function validateTaskAuthority(principal:Principal|undefined,input:{accountId:string;sendMode:string;toolOverrides?:string[]|null}){if(!await canAccessTaskAccount(principal,input.accountId))return"account_forbidden";const defaults=await accountDefaults(input.accountId),tools=effectiveTaskTools(defaults,input.toolOverrides);if(input.sendMode==="auto"&&(!elevated(principal)||!tools.includes("queue_message")))return"auto_send_forbidden";if(!elevated(principal)&&tools.some(tool=>!defaults.includes(tool)))return"tool_expansion_forbidden";return null;}
async function loadTaskForAccess(request:FastifyRequest,reply:FastifyReply,id:string){const result=await pool.query("SELECT * FROM tasks WHERE id=$1",[id]);if(!result.rowCount||!await canAccessTaskAccount(request.principal,result.rows[0].account_id)){await reply.code(404).send({error:"not_found"});return null;}return result.rows[0] as Record<string,unknown>;}
async function validateAssignee(client:import("pg").PoolClient,accountId:string,userId:string|null|undefined){if(!userId)return;const found=await client.query("SELECT 1 FROM users u LEFT JOIN account_permissions p ON p.user_id=u.id AND p.account_id=$2 AND p.can_read WHERE u.id=$1 AND u.disabled_at IS NULL AND (u.role='admin' OR p.user_id IS NOT NULL) LIMIT 1",[userId,accountId]);if(!found.rowCount)throw Object.assign(new Error("invalid_assignee"),{statusCode:400});}
async function validateDependencies(client:import("pg").PoolClient,taskId:string,accountId:string,ids:string[]){if(new Set(ids).size!==ids.length||ids.includes(taskId))throw Object.assign(new Error("invalid_dependencies"),{statusCode:400});if(ids.length){const found=await client.query("SELECT id FROM tasks WHERE account_id=$1 AND id=ANY($2::uuid[])",[accountId,ids]);if(found.rowCount!==ids.length)throw Object.assign(new Error("invalid_dependencies"),{statusCode:400});const cycle=await client.query(`WITH RECURSIVE chain(id) AS (SELECT depends_on_task_id FROM task_dependencies WHERE task_id=ANY($1::uuid[]) UNION SELECT d.depends_on_task_id FROM task_dependencies d JOIN chain c ON c.id=d.task_id) SELECT 1 FROM chain WHERE id=$2 LIMIT 1`,[ids,taskId]);if(cycle.rowCount)throw Object.assign(new Error("task_dependency_cycle"),{statusCode:409});}await client.query("DELETE FROM task_dependencies WHERE task_id=$1",[taskId]);for(const id of ids)await client.query("INSERT INTO task_dependencies(task_id,depends_on_task_id) VALUES($1,$2)",[taskId,id]);}

export async function registerTaskRoutes(app:FastifyInstance){
  app.get("/api/v1/tasks",{preHandler:authenticate},async(request,reply)=>{const query=request.query as {accountId?:string;status?:string;assignedUserId?:string;contactId?:string;source?:string;from?:string;to?:string;q?:string;limit?:string;offset?:string};if(query.accountId&&!await canAccessTaskAccount(request.principal,query.accountId))return reply.code(403).send({error:"account_forbidden"});const limit=Math.min(200,Math.max(1,Number(query.limit)||100)),offset=Math.max(0,Number(query.offset)||0),accountIds=await taskAccountIds(request.principal);const result=await pool.query(`SELECT t.*,a.display_name account_name,COALESCE(NULLIF(co.alias,''),co.display_name,co.phone_e164) contact_name,u.display_name assigned_user_name,COUNT(*) OVER()::int total_count,(SELECT count(*)::int FROM task_dependencies d JOIN tasks p ON p.id=d.depends_on_task_id WHERE d.task_id=t.id AND p.status<>'completed') blocked_by_count FROM tasks t JOIN whatsapp_accounts a ON a.id=t.account_id LEFT JOIN contacts co ON co.id=t.contact_id LEFT JOIN users u ON u.id=t.assigned_user_id WHERE ($1::uuid IS NULL OR t.account_id=$1) AND ($2::uuid[] IS NULL OR t.account_id=ANY($2)) AND ($3::text IS NULL OR t.status=$3) AND ($4::uuid IS NULL OR t.assigned_user_id=$4) AND ($5::uuid IS NULL OR t.contact_id=$5) AND ($6::text IS NULL OR t.source=$6) AND ($7::timestamptz IS NULL OR t.due_at>=$7) AND ($8::timestamptz IS NULL OR t.start_at<=$8) AND ($9::text IS NULL OR t.title ILIKE '%'||$9||'%' OR t.description ILIKE '%'||$9||'%') ORDER BY t.start_at,t.id LIMIT $10 OFFSET $11`,[query.accountId??null,accountIds,query.status??null,query.assignedUserId??null,query.contactId??null,query.source??null,query.from??null,query.to??null,query.q?.trim()||null,limit,offset]);return{data:result.rows,total:Number(result.rows[0]?.total_count??0),hasMore:offset+Number(result.rowCount??0)<Number(result.rows[0]?.total_count??0)};});

  app.get("/api/v1/tasks/:id",{preHandler:authenticate},async(request,reply)=>{const {id}=request.params as {id:string},task=await loadTaskForAccess(request,reply,id);if(!task)return;const [deps,drafts,runs]=await Promise.all([pool.query("SELECT p.id,p.title,p.status FROM task_dependencies d JOIN tasks p ON p.id=d.depends_on_task_id WHERE d.task_id=$1 ORDER BY p.start_at",[id]),pool.query("SELECT * FROM task_drafts WHERE task_id=$1 ORDER BY generated_at DESC",[id]),pool.query("SELECT id,kind,status,tools_used,citations,error,created_at,completed_at FROM task_agent_runs WHERE task_id=$1 ORDER BY created_at DESC LIMIT 30",[id])]);return{...task,dependencies:deps.rows,drafts:drafts.rows,runs:runs.rows};});

  app.post("/api/v1/tasks",{preHandler:authenticate},async(request,reply)=>{if(request.principal?.kind!=="user")return reply.code(403).send({error:"user_required"});const parsed=taskCreateSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"invalid_request",details:parsed.error.flatten()});const auth=await validateTaskAuthority(request.principal,parsed.data as typeof parsed.data&{toolOverrides?:string[]|null});if(auth)return reply.code(403).send({error:auth});const data=parsed.data,created=await transaction(async client=>{await validateAssignee(client,data.accountId,data.assignedUserId);if(data.contactId){const contact=await client.query("SELECT 1 FROM contacts WHERE id=$1 AND account_id=$2",[data.contactId,data.accountId]);if(!contact.rowCount)throw Object.assign(new Error("invalid_contact"),{statusCode:400});}const task=await client.query(`INSERT INTO tasks(account_id,contact_id,conversation_id,assigned_user_id,created_by,kind,title,description,status,progress,start_at,due_at,send_at,send_mode,recurrence,persona_override,tool_overrides) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[data.accountId,data.contactId??null,data.conversationId??null,data.assignedUserId??null,request.principal!.id,data.kind,data.title,data.description,data.status,data.progress,data.startAt,data.dueAt,data.sendAt??null,data.sendMode,data.recurrence?JSON.stringify(data.recurrence):null,data.personaOverride??null,data.toolOverrides??null]);await validateDependencies(client,String(task.rows[0].id),data.accountId,data.dependencyIds);await client.query("INSERT INTO audit_log(actor_type,actor_id,action,target_type,target_id,metadata) VALUES('user',$1,'task.create','task',$2,$3)",[request.principal!.id,task.rows[0].id,JSON.stringify({kind:data.kind,sendMode:data.sendMode,dependencyCount:data.dependencyIds.length})]);return task.rows[0];});return reply.code(201).send(created);});

  app.patch("/api/v1/tasks/:id",{preHandler:authenticate},async(request,reply)=>{if(request.principal?.kind!=="user")return reply.code(403).send({error:"user_required"});const patch=taskUpdateSchema.safeParse(request.body);if(!patch.success)return reply.code(400).send({error:"invalid_request",details:patch.error.flatten()});const {id}=request.params as {id:string},current=await loadTaskForAccess(request,reply,id);if(!current)return;const merged={...rowInput(current),...patch.data,dependencyIds:patch.data.dependencyIds??(await pool.query("SELECT depends_on_task_id FROM task_dependencies WHERE task_id=$1",[id])).rows.map(row=>String(row.depends_on_task_id))},parsed=taskCreateSchema.safeParse(merged);if(!parsed.success)return reply.code(400).send({error:"invalid_request",details:parsed.error.flatten()});const auth=await validateTaskAuthority(request.principal,parsed.data as typeof parsed.data&{toolOverrides?:string[]|null});if(auth)return reply.code(403).send({error:auth});const data=parsed.data,updated=await transaction(async client=>{await validateAssignee(client,data.accountId,data.assignedUserId);const task=await client.query(`UPDATE tasks SET contact_id=$2,conversation_id=$3,assigned_user_id=$4,kind=$5,title=$6,description=$7,status=$8,progress=$9,start_at=$10,due_at=$11,send_at=$12,send_mode=$13,recurrence=$14,persona_override=$15,tool_overrides=$16,updated_at=now() WHERE id=$1 RETURNING *`,[id,data.contactId??null,data.conversationId??null,data.assignedUserId??null,data.kind,data.title,data.description,data.status,data.progress,data.startAt,data.dueAt,data.sendAt??null,data.sendMode,data.recurrence?JSON.stringify(data.recurrence):null,data.personaOverride??null,data.toolOverrides??null]);await validateDependencies(client,id,data.accountId,data.dependencyIds);await client.query("INSERT INTO audit_log(actor_type,actor_id,action,target_type,target_id,metadata) VALUES('user',$1,'task.update','task',$2,'{}')",[request.principal!.id,id]);return task.rows[0];});return updated;});

  app.delete("/api/v1/tasks/:id",{preHandler:authenticate},async(request,reply)=>{if(request.principal?.kind!=="user")return reply.code(403).send({error:"user_required"});const {id}=request.params as {id:string},task=await loadTaskForAccess(request,reply,id);if(!task)return;await pool.query("UPDATE tasks SET status='cancelled',updated_at=now(),last_error='cancelled_by_user' WHERE id=$1 AND status NOT IN ('completed','cancelled')",[id]);return reply.code(204).send();});

  app.post("/api/v1/tasks/:id/generate",{preHandler:authenticate},async(request,reply)=>{const {id}=request.params as {id:string},task=await loadTaskForAccess(request,reply,id);if(!task)return;if(task.kind!=="message")return reply.code(409).send({error:"message_task_required"});await generateTaskDraft(id);return reply.code(202).send({status:"generated"});});
  app.post("/api/v1/tasks/:id/approve",{preHandler:authenticate},async(request,reply)=>{if(request.principal?.kind!=="user")return reply.code(403).send({error:"user_required"});const parsed=taskDraftResolveSchema.safeParse(request.body??{});if(!parsed.success)return reply.code(400).send({error:"invalid_request"});const {id}=request.params as {id:string},task=await loadTaskForAccess(request,reply,id);if(!task)return;if(!task.send_at||new Date(String(task.send_at))<=new Date())return reply.code(409).send({error:"task_send_time_passed",message:"请重新安排发送时间后再审批"});const draft=await transaction(async client=>{const found=await client.query("SELECT id,text_content FROM task_drafts WHERE task_id=$1 AND status='pending' ORDER BY generated_at DESC LIMIT 1 FOR UPDATE",[id]);if(!found.rowCount)return null;const text=parsed.data.text??String(found.rows[0].text_content);await client.query("UPDATE task_drafts SET text_content=$2,status='approved',resolved_at=now(),resolved_by=$3 WHERE id=$1",[found.rows[0].id,text,request.principal!.id]);await client.query("UPDATE tasks SET status='scheduled',approved_at=now(),approved_by=$2,last_error=NULL,updated_at=now() WHERE id=$1",[id,request.principal!.id]);return{id:found.rows[0].id,text};});return draft??reply.code(404).send({error:"pending_draft_not_found"});});
  app.post("/api/v1/tasks/:id/reject",{preHandler:authenticate},async(request,reply)=>{const {id}=request.params as {id:string},task=await loadTaskForAccess(request,reply,id);if(!task)return;await transaction(async client=>{await client.query("UPDATE task_drafts SET status='rejected',resolved_at=now(),resolved_by=$2 WHERE task_id=$1 AND status='pending'",[id,request.principal?.id]);await client.query("UPDATE tasks SET status=CASE WHEN send_at>now() THEN 'planned' ELSE 'overdue' END,approved_at=NULL,approved_by=NULL,updated_at=now() WHERE id=$1",[id]);});return reply.code(204).send();});
  app.post("/api/v1/tasks/:id/reschedule",{preHandler:authenticate},async(request,reply)=>{const parsed=taskRescheduleSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"invalid_request",details:parsed.error.flatten()});const {id}=request.params as {id:string},task=await loadTaskForAccess(request,reply,id);if(!task)return;const updated=await pool.query("UPDATE tasks SET start_at=$2,due_at=$3,send_at=CASE WHEN kind='message' THEN $4 ELSE NULL END,status=CASE WHEN kind='message' AND approved_at IS NOT NULL THEN 'scheduled' ELSE 'planned' END,last_error=NULL,updated_at=now() WHERE id=$1 RETURNING *",[id,parsed.data.startAt,parsed.data.dueAt,parsed.data.sendAt??null]);return updated.rows[0];});
  app.post("/api/v1/tasks/:id/execute",{preHandler:authenticate},async(request,reply)=>{if(request.principal?.kind!=="user")return reply.code(403).send({error:"user_required"});const {id}=request.params as {id:string},task=await loadTaskForAccess(request,reply,id);if(!task)return;if(task.kind==="general"){await completeGeneralTask(id,request.principal.id);return{status:"completed"};}const result=await dispatchTask(id,request.principal.id);return reply.code(202).send(result);});

  app.get("/api/v1/accounts/:id/task-settings",{preHandler:authenticate},async(request,reply)=>{const {id}=request.params as {id:string};if(!await canAccessTaskAccount(request.principal,id))return reply.code(403).send({error:"account_forbidden"});await pool.query("INSERT INTO account_task_settings(account_id) VALUES($1) ON CONFLICT DO NOTHING",[id]);return(await pool.query("SELECT * FROM account_task_settings WHERE account_id=$1",[id])).rows[0];});
  app.put("/api/v1/accounts/:id/task-settings",{preHandler:authenticate},async(request,reply)=>{if(!elevated(request.principal))return reply.code(403).send({error:"supervisor_required"});const {id}=request.params as {id:string};if(!await canAccessTaskAccount(request.principal,id))return reply.code(403).send({error:"account_forbidden"});const parsed=accountTaskSettingsSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"invalid_request",details:parsed.error.flatten()});const data=parsed.data;if(data.defaultSendMode==="auto"&&!data.defaultTools.includes("queue_message"))return reply.code(400).send({error:"queue_message_required"});const saved=await transaction(async client=>{const result=await client.query(`INSERT INTO account_task_settings(account_id,holiday_regions,enabled_holidays,default_lead_days,draft_lead_hours,default_send_mode,leap_day_policy,default_tools) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(account_id) DO UPDATE SET holiday_regions=EXCLUDED.holiday_regions,enabled_holidays=EXCLUDED.enabled_holidays,default_lead_days=EXCLUDED.default_lead_days,draft_lead_hours=EXCLUDED.draft_lead_hours,default_send_mode=EXCLUDED.default_send_mode,leap_day_policy=EXCLUDED.leap_day_policy,default_tools=EXCLUDED.default_tools,updated_at=now() RETURNING *`,[id,data.holidayRegions,data.enabledHolidays,data.defaultLeadDays,data.draftLeadHours,data.defaultSendMode,data.leapDayPolicy,data.defaultTools]);await client.query("UPDATE task_rules SET enabled=false,updated_at=now() WHERE account_id=$1 AND source='holiday' AND NOT(source_key=ANY($2::text[]))",[id,data.enabledHolidays]);await client.query("UPDATE tasks SET status='cancelled',last_error='holiday_disabled',updated_at=now() WHERE account_id=$1 AND source='holiday' AND NOT(source_key=ANY($2::text[])) AND status IN ('planned','in_progress','waiting_approval','scheduled','overdue')",[id,data.enabledHolidays]);return result.rows[0];});return saved;});

  app.get("/api/v1/task-tools",{preHandler:authenticate},async()=>({data:TASK_TOOLS}));
  app.get("/api/v1/task-assignees",{preHandler:authenticate},async()=>({data:(await pool.query("SELECT id,display_name,email,role FROM users WHERE disabled_at IS NULL ORDER BY lower(display_name),lower(email)")).rows}));
  app.get("/api/v1/task-rules",{preHandler:authenticate},async(request)=>{const accountIds=await taskAccountIds(request.principal);return{data:(await pool.query("SELECT r.*,COALESCE(NULLIF(co.alias,''),co.display_name,co.phone_e164) contact_name FROM task_rules r LEFT JOIN contacts co ON co.id=r.contact_id WHERE ($1::uuid[] IS NULL OR r.account_id=ANY($1)) ORDER BY r.created_at DESC",[accountIds])).rows};});
  app.post("/api/v1/task-rules",{preHandler:authenticate},async(request,reply)=>{if(request.principal?.kind!=="user")return reply.code(403).send({error:"user_required"});const body=(request.body??{}) as {accountId?:string;contactId?:string;holiday?:string;leadDays?:number;sendMode?:string;enabled?:boolean};if(!body.accountId||!body.contactId||!["new_year","valentines","halloween","christmas"].includes(body.holiday??""))return reply.code(400).send({error:"invalid_request"});if(!await canAccessTaskAccount(request.principal,body.accountId))return reply.code(403).send({error:"account_forbidden"});if(body.sendMode==="auto"&&!elevated(request.principal))return reply.code(403).send({error:"auto_send_forbidden"});const title=({new_year:"新年祝福",valentines:"情人节问候",halloween:"万圣节问候",christmas:"圣诞节祝福"} as Record<string,string>)[body.holiday!];const saved=await pool.query(`INSERT INTO task_rules(account_id,contact_id,source,source_key,title_template,lead_days,send_mode,enabled,created_by) VALUES($1,$2,'holiday',$3,$4,$5,$6,$7,$8) ON CONFLICT(account_id,contact_id,source,source_key) DO UPDATE SET lead_days=EXCLUDED.lead_days,send_mode=EXCLUDED.send_mode,enabled=EXCLUDED.enabled,updated_at=now() RETURNING *`,[body.accountId,body.contactId,body.holiday,title,body.leadDays??null,body.sendMode??"approval",body.enabled!==false,request.principal.id]);return reply.code(201).send(saved.rows[0]);});
  app.delete("/api/v1/task-rules/:id",{preHandler:authenticate},async(request,reply)=>{const {id}=request.params as {id:string},rule=await pool.query("SELECT account_id FROM task_rules WHERE id=$1",[id]);if(!rule.rowCount||!await canAccessTaskAccount(request.principal,rule.rows[0].account_id))return reply.code(404).send({error:"not_found"});await pool.query("UPDATE task_rules SET enabled=false,updated_at=now() WHERE id=$1",[id]);return reply.code(204).send();});
}
